### ISSUE TITLE
kweb down?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1034]
I kompiled imp.k in lesson 4, then picked collatz.imp in lesson 1 and got this error:

Running command: krun collatz.imp -d ../../lesson_4
[Error] Critical: You can only specify $PGM on the command line itself
----- End of process output.

**Comment by pdaian** [comment]
@grosu - Fixed.  Issue was a change in K input handling.  We lost the following functionality due to the change:
- Users can kompile or krun files without entering the filenames in the parameters box (will default to open file).

I made an issue here: kframework/kweb#13 and we can discuss whether this is an important feature.
