### ISSUE TITLE
`kil.Attribute` needs to be at least Serializable, and we need clean text keys

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1043]
As we intend the .kore files to be the communication format between the various K passes, we need the ability to both turn Attributes to text and back. This would have been easy before the refactoring that added typing the Attribute keys. Now, it may not be that easy. To make this work we need:
1. All attribute values to be serializable
2. All attribute keys to be valid KLabels (this might be easy using backticks, but I'm not sure if stranger things won't confuse the parser. @radumereuta?)
3. We need a 1-to-1 mapping between text keys and typed keys. Most importantly, we need a unified way to create the right key object from a piece of text. 

@dwightguth, I think you are most familiar with this code as you refactored to add types. How can we get the above?

**Comment by dwightguth** [comment]
I suggest you take a look at Attribute.Key#toString in the repository. This
can of course be modified as a method however we'd like, but I believe I
have something that should serve as a basic 1-1 mapping between strings and
typed attribute keys. Since we already have an injection from Strings to
KLabels, that should serve also as #2. As far as #1 goes, I believe we
should invest in some kind of system for automatically converting between
untyped data in the form of text, and strongly typed bean classes
containing immutable data. How to go about doing that part I leave to your
discretion.

And again, I should point out as well that the entire Attribute/Attributes
class can be replaced in my opinion as long as it is replaced with
something new that satisfies all of the appropriate constraints.

**Comment by dwightguth** [comment]
@cos does this answer your question? Or do you have something more concrete you want me to do?

**Comment by cos** [comment]
Ideally, the mapping from text back to typed keys should be done without needing a grand map of string to keys -- reflection might work. 

In any case, let's postpone the discussion for now. I'll leave this open.
