### ISSUE TITLE
80 characters in error messages, please!!!!

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#106]
fslwork$ krun
[Error] Critical: Could not find compiled definition for backend 'maude'.  Please ensure this backend has been kompiled.
fslwork$ pwd
/home/grosu/k/tests/regression/java-rewrite-engine/visitor
fslwork$ ls
imp.k  imp-kompiled  imp.pdf  sum.imp  sum.imp.out
fslwork$

**Comment by ericmikida** [comment]
Hmm that's odd. I had already fixed that error here: 

https://github.com/kframework/k/blob/6a43d8c401ad825de6f36cd097b65e0a83175ba1/javasources/KTool/src/org/kframework/krun/Main.java#L1062

I'll push another fix tonight.

**Comment by dwightguth** [comment]
I recommend you create a function for formatting error strings that does
this automatically, if it's a priority. Otherwise this will keep happening
forever.

**Comment by dwightguth** [comment]
Hmm, actually you might be able to solve the problem without sacrificing
the ability to place line breaks manually by investing in the right set of
unit tests.

**Comment by ericmikida** [comment]
I pushed a temporary fix for this particular error message, but I agree that something more general should be done. I had considered modifying our error reporting function to format messages when I first addressed this issue, but I was brand new to the group and didn't want to make such a big change right off the bat.

I think I'll start exploring that option again, but it's usefulness also relies on the fact that errors are reported in some sort of consistent way. IIRC most are reported using the Error.report() method, but that may have changed since.
