### ISSUE TITLE
K new parser cannot deal with octal decimal representation in a string

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1078]
When I have the following definition:

```
module TEST

     syntax KItem ::= String
     rule S:String => .K 

endmodule
```

If I run the following program:

```
"\000\377"
```

Both Maude and Java backend will tell me the following:

```
[Error] Critical: Parse error: Syntax error near unexpected character '0'
    Source: File: /home/qangel/project/csemantics/bin/a.test
    Location: (1,3,1,3)

```

Since the C parser parses a C program like:

```
#include <stdlib.h>
static const unsigned char f[] = "\0\377";
static const unsigned char g[] = "\0ÿ";
....
```

to a intermediate representation with the octal decimal representation in a string in the intermediate representation, so I will assume that K was able to parse the program when the guy was designing the C semantics. I wonder what is the new solution to parse such Octal or Hex decimal representation for string.

**Comment by radumereuta** [comment]
This is the java regex which matches on strings:
`regex("[\\\"](([^\\\"\\n\\r\\\\])|([\\\\][nrtf\\\"\\\\])|([\\\\][x][0-9a-fA-F]{2})|([\\\\][u][0-9a-fA-F]{4})|([\\\\][U][0-9a-fA-F]{8}))*[\\\"]")`

If you want to specify the code for a specific character, then the K way is to use something like: `"\x0F"`, `"\u00FF"`, or `"\U00ff00FF"`. Since C uses different styles of strings, I guess you will have to declare your own strings, and convert them into something that can be represented in K.

So this is not a bug in the parser. You will have to declare your own strings. You can take as an example the already existing ones from `/include/builtins/string.k`.

**Comment by liyili2** [comment]
Do you know whether or not there is an Octal decimal system for K?

**Comment by dwightguth** [comment]
Again, I will repeat what Radu said. The "String" type represents K
strings, not strings in the programming language under design. K strings do
not have octal escapes. However, you can use the functions Base2String and
String2Base to convert octal numbers in string representation into the
domain of integers. Using this plus a Token for your own custom string type
should be sufficient to give you the behavior you desire.
