### ISSUE TITLE
incorrect line number in error report

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#108]
Compiling the CIL definition at https://github.com/kframework/c-semantics/tree/java_rewrite_engine results in an error:
Sona:cil-semantics andrei$ kompile cil.k
[Error] Critical: Parse error: Syntax error near unexpected character ')'
    File: /Users/andrei/c_semantics_java_rewrite_engine/cil-semantics/cil-common.k
    Location: (246,63,246,63)
However, line 246 in https://github.com/kframework/c-semantics/blob/java_rewrite_engine/cil-semantics/cil-common.k contains the sole keyword rule.
I believe I have encountered similar inaccurate line numbers before, and it makes debugging unnecessarily hard. I would appreciate this fixed as soon as possible.

**Comment by andreistefanescu** [comment]
To be precise, it is commit https://github.com/kframework/c-semantics/commit/1fcdc04c10ba7feeaaf4796b6c6dd26de2a3afe7.

**Comment by radumereuta** [comment]
I had a look and I've traced the error back to the new Basic parser.
When parsing a StringSentence, I'm expecting the location information to be related only to the content of the rule. That means the label and the attributes should not be counted.

Michael, I've tried to modify the javacc code, but I got stuck in 'makeStringSentence' where you use a regular expression to match the label of a rule, and I don't know how to get the location of the first token anymore.

Can you have a look?
The issue can be easily replicated with this simple module:
module TEST
rule [r1]: +z [att]
rule [r2]:
+z
[att]
endmodule

The location information for the StringSentence in this case should indicate to '+'. Substring would not work in this case because of rule 2.

**Comment by andreistefanescu** [comment]
Michael, did you get a chance to took at it? It should not take you very long.

**Comment by adamsmd** [comment]
I haven't had a chance to look at it, but I have a good idea where the 
problem is.

**Comment by andreistefanescu** [comment]
Please try to fix it as soon as you can, it is a rather annoying issue. :)

**Comment by adamsmd** [comment]
I think I've fixed the issue with my latest push, but I haven't tested it.  @andreistefanescu could you let me know if the fix works?  (Their might be off-by-one errors.)

**Comment by radumereuta** [comment]
I've tested this and it should work now. I found where the off-by-one error was, and now all location information should be precise.

**Comment by adamsmd** [comment]
That fix doesn't look right to me.  I've pushed a patch with an alternate fix.  Can you check if it works?

**Comment by radumereuta** [comment]
It appears to be working correctly now.
