### ISSUE TITLE
kompile --- list parsing ambiguity

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#109]
The least sort of a list does not seem to be calculated correctly.

Consider the following module:

module TRY
  syntax Exp ::= Id
  syntax Type ::= Id

  syntax Ids ::= List{Id,","}
  syntax Types ::= List{Type,","}
  syntax Exps ::= List{Exp,","}

  configuration <k> $PGM:K </k> <cell> .Ids </cell>

  rule <cell> X:Id,Xs:Ids => .Ids </cell>

endmodule

When we kompile, we get the following ambiguity:

[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: Exps ::= List{Exp,","}  
   X:Id, Xs:Ids
2: Types ::= List{Type,","}  
   X:Id, Xs:Ids
    File: /home/grosu/try/try.k
    Location: (11,10,11,21)
    Compilation Phase: Ambiguity filter

None of the sorts Exps and Types should be inferred there, because Ids is a subsort of both Types and Exps.  Besides, the cell <cell> takes Ids (but this should be irrelevant).

**Comment by radumereuta** [comment]
The behavior you are asking me to implement, directly contradicts another case found in simple-untyped:
rule <k> print(V:Val, Es => Es); ...</k> <out>... . => ListItem(V) </out>

In this case you are evaluating elements from print. You match on the first element and you want them to be a value in order to be printable, but the rest of the list should be an Exps, because it hasn't been evaluated yet.

In this case I also have an ambiguity between Vals and Exps. In order to be able to infer sort Exps to variable Es, is only if I chose Exps over Vals, meaning the most general production from the two. This means that I'm trying to maximize the terms that I can match.

**Comment by grosu** [comment]
No, there is no contradiction here.

1) When you infer the sort of a variable, you should produce the LARGEST sort that variable can have so that things parse (ambiguously or not).  If things parse ambiguously, you should report an error/warning message, telling that the inferred sort yields an ambiguity.  In other words, you should NOT search for a less general sort until things parse non-ambiguously, because that would confuse people; it is better to have them say what sort they meant instead of inferring something strange.  Similarly, if there is no largest sort that a variable can have, then report an error/warning message.

2) When you know all the sorts of all the variables, you then infer the LEAST sort of the term.

So in the case of X:Id,Xs:Ids you apply the second principle above and get the sort Ids for this term.  In the case of print(V:Val,Es), you would infer for Es the sort Exps, because that is the largest one that makes things parse, according to the first principle.

**Comment by radumereuta** [comment]
Should be fixed with #698
