### ISSUE TITLE
Update the readme on how to set up a running environment in an IDE

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#1093]
I had some troubles today setting up my IntelliJ to run kompile and krun.
The problem is that recently the running scripts have been updated to include the path to the executables required by K. Basically the resolution of which executable to run depending on the platform has been moved to bash scripts, and now this has to be simulated by the IDE.

I think this should be better explained in readme for developers.

**Comment by grosu** [comment]
bash scripts?  There should not be any bash scripts, except for the ones calling the java command corresponding to kompile or krun.  Guys, please spend some time to make the overall setting as easy to use as possible, because these sort of low-hanging fruits save everybody, including yourself time.  I'm definitely going to complain if it will not be straightforward to build and execute the project.  There should be no complexity whatsoever there.

Grigore

**Comment by radumereuta** [comment]
This only affects the IDE configuration.
@dwightguth did this in order to simplify adding and removing dependencies from the tool, but he had to add code in multiple places that handle these external dependencies.
All I want is for this to be documented somehow.
