### ISSUE TITLE
krun --- uncaught exception with sort in search patterns

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#114]
Exceptions are thrown if I put any other sort but K for the variables that appear in search patterns:

fslwork$ krun -d ../1_untyped/1_environment/ list-4.fun --search --pattern "<k>V:Val</k>"
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.krun.api.KRunState.concretize(KRunState.java:46)
    at org.kframework.krun.api.SearchResult.getSubstitution(SearchResult.java:54)
    at org.kframework.krun.api.SearchResults.toString(SearchResults.java:33)
    at org.kframework.krun.api.KRunResult.toString(KRunResult.java:41)
    at org.kframework.krun.Main.normalExecution(Main.java:381)
    at org.kframework.krun.Main.execute_Krun(Main.java:1126)
    at org.kframework.main.Main.main(Main.java:59)
fslwork$ 
fslwork$ 
fslwork$ krun -d ../1_untyped/1_environment/ list-4.fun --search --pattern "<k>V:Exp</k>"
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.krun.api.KRunState.concretize(KRunState.java:46)
    at org.kframework.krun.api.SearchResult.getSubstitution(SearchResult.java:54)
    at org.kframework.krun.api.SearchResults.toString(SearchResults.java:33)
    at org.kframework.krun.api.KRunResult.toString(KRunResult.java:41)
    at org.kframework.krun.Main.normalExecution(Main.java:381)
    at org.kframework.krun.Main.execute_Krun(Main.java:1126)
    at org.kframework.main.Main.main(Main.java:59)
fslwork$ 
fslwork$ 
fslwork$ krun -d ../1_untyped/1_environment/ list-4.fun --search --pattern "<k>V:K</k>"
Search results:

Solution 1, State 0:
V:K -->
3
fslwork$

**Comment by ericmikida** [comment]
OK. I've found the source of the problem I'm just not quite sure how to fix it. It may involve parsing so I'm tagging @radumereuta.

What happens when a pattern is parsed, is that it turns the sorts of variables into KItems (unless the sort was K, then it leaves the variable untouched).

So running this command:

krun -d ../1_untyped/ list-4.fun --search --pattern "<k> V:Val </k>"

Ends up withe following rule as the pattern:

rule <generatedTop> <T> <k> V:KItem  </k> GeneratedFreshVar0:Bag  </T>  </generatedTop>  requires isVal(V:KItem ) [ location((1,1,1,15)),  filename(Command line pattern)]

Eventually resulting in the following search command to be run by Maude:

=>! <_>_</_>(generatedTop, (<_>_</_>(T, (<_>_</_>(k, V:KItem, k)) (GeneratedFreshVar0:Bag) , T)) , generatedTop) such that _`(_`)(isVal, V:KItem) = # true(.KList)

Notice how the sort of V is KItem, and then there is an extra clause requiring isVal(V) == true

The problem is once the search is complete, this clause is lost, and the search result just contains a variable V:KItem, so then when we try to get "V:Val" from the substitution map to do pretty printing, we end up not finding anything, and eventually getting a NullPointerException.

The way I see it there are two ways to fix the problem.

1) Is it possible to just change the parsing so that the generated patternRule is:
rule <generatedTop> <T> <k> V:Val  </k> GeneratedFreshVar0:Bag  </T>  </generatedTop> [ location((1,1,1,15)),  filename(Command line pattern)]

This way we just sort V directly rather than sorting it to a KItem and requiring that it isVal(V) == true. This would probably be on Radu's end since he is more familiar with the parsing.

2) From KRun's standpoint, we know that once the search is complete, things have been correctly typed by maude already. So instead of trying to get "V:Val" from the substitution map, I could just have it look up "V:KItem" instead (which we know is there). We know to complete the search V had to be type-able to Val in maude. This would be a really quick fix, I just don't know if it is the best way of doing things, since it seems a little "hacky"

Eric

**Comment by ericmikida** [comment]
Hmm...some of the brackets didn't show up quite right, but I think everything makes sense. Let me know if you need more clarification.

**Comment by radumereuta** [comment]
The backend doesn't have sorts. It only works with predicates like isVal(V) == true. Something like V:Val doesn't have any meaning in maude right now. At one point it had, but we moved towards this predicate based sorts. So 1) is not the solution.

The second part I think it's the right way. And it's not hacky, it's just how the backend works. It transforms things like V:Val into isVal(V:KItem) == true. You have to map this transformation and retrieve the correct results.
