### ISSUE TITLE
Possible redundant state in kil.Cell

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1144]
Found these suspicious fields in `kil.Cell`:

```
    /** Must equal with {@link #endLabel} */
    String label;
    /** Must equal with {@link #label} */
    String endLabel;
```

Is there a reason to keep both of them? @radumereuta do you have any ideas?

**Comment by dwightguth** [comment]
The simple solution is to delete endLabel and move the check which asserts
they are equal to the XML constructor of Cell. You need to make sure a
friendly error message is printed if they are not however.

**Comment by radumereuta** [comment]
I suggest against.
It is possible that the user may define some sort of syntax that overlaps with the cell syntax. In that case I may be able to disambiguate the erroneous parses with the `CellEndLabelFilter`.
If you throw the exception from the constructor, then you will reject an entire parse forest, even though there might be a correct parse in there.

**Comment by dwightguth** [comment]
I'm not sure I follow. If the parse forest contains mismatched start and
end tags, doesn't that mean that somewhere else is the correct parse forest?

**Comment by osa1** [comment]
Radu, is it possible to observe a difference between these two fields in program's lifetime? (e.g. when one of the fields are read, other one is different)

If yes, then either we need to change the comments(because it's wrong) or we have a bug.
If no, then why not remove one of them? They'll be always same.

In any case, not a big deal, but from a reader's perspective it looks weird.

**Comment by radumereuta** [comment]
@dwightguth yes, but I'm using the visitor system (that has the throw exception in problematic area, and catch in amb nodes). This makes it really easy to disambiguate.

@osa1 it is possible. Once if the user makes a mistake, then we throw an error message. The second example is the one I told you before where is just a weird parsing ambiguity, but which can be fixed with proper filtering.

I saw that @bmmoore added those comments, and I agree, they are on the light side of descriptiveness. My argument of having both, is that it must match the syntax declaration of a cell, which has 4 arguments: `"<" StartLabel Arguments ">" Contents "</" endLabel ">"`.
Having only one name for a cell is a semantic abstraction.

How we want to do it in the future is opened to discussion. A cleaner way with the new parser would be to parse Cells as TermConses and have a special filter which looks at the TermCons, determine it is a Cell, and check to see if the first and last argument matches. But currently the SDF parser is set to instantiate the Cell class directly.

Please let me know if I'm making any sense.

**Comment by dwightguth** [comment]
So I think this is probably fine for now with the understanding that in the
new parser cells will just be productions such as:

syntax KCell ::= "<k>" K "</k>" [cell]

**Comment by radumereuta** [comment]
I'm not sure about the exact format, but probably something like that.
So is this discussion thread closeable?
