### ISSUE TITLE
parsing problem with lists

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#119]
Executing "a, a b" with the following

module ISSUE
  syntax A  ::= "a"
  syntax As ::= List{A,","}

  syntax B  ::= As "b"
  syntax Bs ::= List{B,","}
endmodule

parses it to "(a,a) b".  It should report an ambiguity.

Trying to convince it to parse how I want using brackets,

module ISSUE  
  syntax A  ::= "a"  
  syntax As ::= List{A,","}                                                    

  syntax B  ::= As "b" | "(" B ")" [bracket]  
  syntax Bs ::= List{B,","}  
endmodule                                                                      

and then modifying the program to "a, (a b)" makes it report a parsing error, although it should be parsable:

fslwork$ krun p
[Error] Critical: Parse error: Syntax error near unexpected character '('
    File: p
    Location: (1,4,1,4)

fslwork$ 

p.s. I don't know how I can make these into testable issues.  For now I'm just adding them there without any checks, but with comments.

**Comment by radumereuta** [comment]
Hmm... but it shouldn't report any ambiguities. "a, a b" is not ambiguous. When you are trying to force it with brackets, you are violating the sorts. The List{A,","} can only accept elements of type A, but you are trying to force an element of type B, which has no subsort relation with A.

Are you missing some other productions? Because what you wrote there is correct.
