### ISSUE TITLE
heating/coling rules do not work as expected

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#124]
Compiling the definition (stored in hc.k)

```
module HC

  syntax Exp ::= Val | Id 
               | Exp "+" Exp [left, plus]

  syntax Val ::= Int
  syntax Id ::= "x"

  configuration
    <k> $PGM:Exp </k>

  rule I1:Int + I2:Int => I1 +Int I2

  syntax K ::= "rvalue" "(" K ")" [klabel(rvalue)]

  rule E1:Exp + E2:Exp => rvalue(E1) ~> HOLE + E2 when isVal(E1) =/=K true [heat]
  rule V1:Val ~> HOLE + E2:Exp => V1 + E2 [cool]

  rule rvalue(X:Id) => 10

endmodule
```

and executing the program "x+3" (stored in ex.hc) we get 

```
$ kompile hc
$ krun ex.hc 
<k>
    10 ~> HOLE + 3
</k>
```

As you can see, the cooling rule didn't applied. Is something I miss here?

**Comment by traiansf** [comment]
For heating and cooling rules we don't specify the result (because the
result is just a strategy in the heating/cooling process).  So Val should
be added to KResult and your rules should be rewritten as:

  rule E1:Exp + E2:Exp => rvalue(E1) ~> HOLE + E2 [heat]
  rule V1:Exp ~> HOLE + E2:Exp => V1 + E2 [cool]

Not sure if this helps, though.

Best wishes,

Traian

2013/11/4 Dorel Lucanu notifications@github.com

**Comment by dlucanu** [comment]
Thanks.
I only added "syntax KResult ::= Val" and it worked fine.
I close it.

**Comment by traiansf** [comment]
I was just saying that if you add KResult ::= Val it shouldn't be necessary
to add the sort conditions to the heat/cool rules, as they are
automatically generated.

best wishes,
Traian

2013/11/4 Dorel Lucanu notifications@github.com

**Comment by dlucanu** [comment]
Yes, I know that, but I wrote them in this way having in mind their 
parametrization.

Dorel
