### ISSUE TITLE
[Error] Critical: unexpected left-hand side data structure format; expected elements and at most one variable

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1283]
What does that error mean?

```
[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable
[][GeneratedAnonVar246:List, GeneratedAnonVar549:List, GeneratedAnonVar247:List][]
```

The following simplified rule produces that error:

```
rule
  <myListCell>... ListItem(X:Int) => .List ...</myListCell>
```

This compiled successfully with the latest release of 3.5. But in the latest master, that is 3.6-snapshot, which I compiled less than two hours ago, this error appeared. 
But removing the `...` whether at the beginning or at the end of the cell fixes it. So I guess this is an intended behavior. Can you explain why that is?

**Comment by dwightguth** [comment]
You are attempting to match an element in the middle of the list, which is a nondeterministic choice that performs associative matching. K 3.6 does not currently support this behavior.

You should be able to rewrite this particular rule so that that does not occur. Consider:

```
rule <myListCell> L:List => stripInts(L) </myListCell>
syntax List ::=  stripInts(List) [function]
rule stripInts(ListItem(_:Int) L:List) => stripInts(L)
rule stripInts(.List) => .List
rule stripInts(ListItem(K) L:List) => ListItem(K) stripInts(L) requires notBool isInt(K)
```

If you run into other rules where this is occurring which cannot be rewritten easily in this manner, please let us know. You may be one of those people for whom K 3.6 is not able to support your use case, in which case we will likely try to determine a way to get K 3.5 to support your needs.

**Comment by omarzd** [comment]
Thanks for clearing that up. What I want to do is move an arbitrary item (nondeterministically chosen) from one thread to another. Can I achieve that with 3.5? I want to be shown multiple solutions using `--search`. Right now, I'm getting only one solution.
I used to do it like this:

```
<myListCell> _ ListItem(V:Val) => .List </myListCell>
```

So I'm taking one item arbitrarily and deleting the rest. This used to work before. I even got it from Traian [here](http://lists.cs.uiuc.edu/pipermail/k-user/2014-November/000696.html). I was using 3.5-Snapshot then.
One more question; do you mean that 3.6 stripped features like associative matching from 3.5?!

**Comment by dwightguth** [comment]
K 3.6 is implemented internally using a different rewrite engine than the Maude-based K 3.5. This is why we have decided to continue supporting K 3.5 for users who are having trouble converting their definitions to K 3.6, and is also why you are running into some of the issues that you are running into. This new rewrite engine does not support every single feature that the old one did, and so some features are temporarily not working. We intend to fix this situation before the release of K 4.0, but in the meantime, this particular feature is only supported in K 3.5.

One workaround you can do in order to make this rule work with K 3.6 is to convert the List to a Set before you make the nondeterministic choice. That will bypass the issue you are running into now. Note that it will not necessarily guarantee the same result if you are relying on the non-idempotent nature of Lists, however. But if you are simply using the List as a Set or as a List with no duplicate elements, it should be possible to achieve the same behavior this way.

@andreistefanescu it sounds like what he needs is a list choice operation. Is there a way for us to do this simply, or would it require the entire associative-matching apparatus?

**Comment by omarzd** [comment]
By the way, I moved back to 3.5, but I'm still not getting nondeterminism. How can I nondeterminstically choose an item from the list and delete the others (including it). It used to work on 3.5 two months ago with this:

```
<myListCell> _ ListItem(V:Val) => .List </myListCell>
```

**Comment by dwightguth** [comment]
is this rule marked as a transition? You will not get diverging paths in the state space otherwise.

**Comment by dwightguth** [comment]
I'm not quite sure why that rule should have caused nondeterminism before; that seems incorrect to me. What that rule is doing is always choosing the last element of the list. If you want a nondeterministic choice, you want the following rule:

```
rule <myListCell> _ (ListItem(V:Val) => .List) _ </myListCell>
```

**Comment by omarzd** [comment]
Yes but I also want to remove all items in the list at the same time. So I did:

```
rule <myListCell> _ ListItem(V:Val) _  => .List </myListCell>
```

but the rule didn't even match. The items just sat there. Even when I tried your suggestion, it didn't match. Even when I did this, it didn't match:

```
rule <myListCell>... ListItem(V:Val) => .List ...</myListCell>
```

**Comment by omarzd** [comment]
I may be wrong about that rule giving me nondeterminism, but I lost the state of the program where I had nondeterminism, and I want to get it back. Now why would `_ ListItem(V:Val)` match but `_ ListItem(V:Val) _` not?! In the example I'm running, I have only two items in the list.

**Comment by omarzd** [comment]
Here is the state getting stuck:

```
        <thread>
            <k>
                prllCompMgr ( 5 )
            </k>
            <publish>
                ListItem ( 10 )
                ListItem ( 20 )
                ListItem ( 30 )
                ListItem ( 40 )
                ListItem ( 50 )
            </publish>
            <props>
                SetItem ( "prunRightExp" )
            </props>
        </thread>
```

And here is the rule that's not matching:

```
        <thread>...
            <k> _:K => .K </k>
            <publish> _:List ListItem(V:Val) _:List => .List </publish>
            <props>... SetItem("prunRightExp") ...</props>
        ...</thread>
        <thread>...
            some other place where V is used
        ...</thread>
```

while this one is matching:

```
        <thread>...
            <k> _:K => .K </k>
            <publish> _:List ListItem(V:Val) => .List </publish>
            <props>... SetItem("prunRightExp") ...</props>
        ...</thread>
        <thread>...
            some other place where V is used
        ...</thread>
```

How is that happening?!

**Comment by omarzd** [comment]
Wait a second. I think it is matching one time for each item in the list. Let me check.

**Comment by omarzd** [comment]
I must add that these items are only ordered like that because K chose so. They should have been added in an arbitrary order because each comes from a different thread.

**Comment by omarzd** [comment]
The problem is related to other rules. The whole design needs revision. Will close this for now. Thank you.

**Comment by omarzd** [comment]
I marked one rule as `transition`, the one that adds `Vals` to my `publish` cell; and now `--search-all` gives 326 solutions! A bit more than what I asked for.
