### ISSUE TITLE
Attribute "anywhere" too relaxed

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#130]
Currently, the "anywhere" attribute is too relaxed, as it allows the rules to apply literally anywhere, including in cells that have nothing to do with computations.  For example, the following would be a very nice K definition of a type checker for a simply-typed lambda calculus extended with builtins and recursion:

require "modules/substitution.k"

module LAMBDA
  imports SUBSTITUTION

  syntax Type ::= "int" | "bool"
                | Type "->" Type
                | "(" Type ")"                 [bracket]

  syntax Exp ::= Id
               | "lambda" Id ":" Type "." Exp  [binder]
           | Exp Exp                       [left]
           | "(" Exp ")"                   [bracket]

  syntax Exp ::= Type

  syntax KResult ::= Type

  syntax Exp ::= Exp "->" Exp
  rule lambda X : T . E => T -> E[T/X]         [anywhere]
  rule (T1 -> T2) T1 => T2                     [anywhere]

  syntax Exp ::= Int | Bool
           | Exp "*" Exp                   [left]
           | Exp "/" Exp
           > Exp "+" Exp                   [left]
           > Exp "<=" Exp

  rule _:Int => int                            [anywhere]
  rule _:Bool => bool                          [anywhere]
  rule int \* int => int                        [anywhere]
  rule int / int => int                        [anywhere]
  rule int + int => int                        [anywhere]
  rule int <= int => bool                      [anywhere]

  syntax Exp ::= "if" Exp "then" Exp "else" Exp
  rule if bool then T:Type else T => T         [anywhere]

  syntax Exp ::= "let" Id ":" Type "=" Exp "in" Exp
  rule let X : T = E in E' => (lambda X : T . E') E                   [macro]

  syntax Exp ::= "letrec" Id ":" Type Id ":" Type "=" Exp "in" Exp
           | "mu" Id ":" Type "." Exp      [binder]
  rule letrec F : T1  X : T2 = E in E'
    => let F : T1 = mu F : T1 . lambda X : T2 . E in E'               [macro]
  rule mu X : T . E => (T -> T) E[T/X]         [anywhere]
endmodule

However, it does not work because the "anywhere" attribute in these rules

  rule _:Int => int                                [anywhere]
  rule _:Bool => bool                          [anywhere]

makes any integer appearing anywhere to be rewritten into "int".  We obviously only mean the intergers that appear in the <k> cell.

I am not sure whether this is a matter of strategies or of core functionality of the rewrite engine.  I assigned Eric to it, but Andrei S can as well look into this.

**Comment by ericmikida** [comment]
At first glance to me this seems more like a core functionality thing. Strategies, at least right now, decide what rules may be applied but not how they are applied. To me this problem seems more like an issue of how the [anywhere] rule is applied.

Also another thing that comes to mind is how are these [anywhere] rules indexed? It seems to me like they would still be indexed like a normal rule, based on the first KLabel in the <k> cell. I would think this would be the main thing that would screw up when these rules are applied.

For example, if we are currently in a state like this:

<k> someKLabel ~> I:Int ...</k>

We would want the [anywhere] rule to be able to rewrite I:Int to int. However, the first index of this term is based on someKLabel. So the [anywhere] rule wouldn't even be considered because of the way indexing is done. I would think this would also prevent the rule from applying to other cells in many cases, unless it just so happens that there is a variable of sort Int on top of the K cell.
