### ISSUE TITLE
unparser does not unparse correctly

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1319]
If you krun the program `closed-variable-capture.lambda`, which is `(lambda z.(z z)) (lambda x.lambda y.(x y))`, with our very first language definition in the tutorial, `1_k/1_lambda/lesson_1`, the result is `lambda z . (z z) lambda x . lambda y . (x y)`.  This is incorrect; for example, it does not even parse correctly.  @laurayuwen, this is something you will have to soon start looking into.  (@dwightguth, I asked @laurayuwen to look into unparsing as a potential research topic for her)

**Comment by dwightguth** [comment]
so, I don't know offhand exaghry why this is happening, because I am pretty sure the naive unparsing algorithm used by --output pretty should be able to handle at least this simple of a case, but I will comment that in general --output pretty is not intended to be sound, it's intended to run with as fast an asymptotic running time as possible (I haven't done the math but I think it's n log n). I ran this example with --output sound, which is intended to be the full NP-hard unparsing algorithm, and it generates an unambiguously parseable result.

@laurayuwen you should investigate why AddBracketsFilter is determining that it does not need a bracket around `lambda z . (z z)`. I suspect it relates to the recent modifications I made to that class to make it run in linear time, which must not have handled a case correctly. See if you can find a way to fix the algorithm without getting rid of the linear time requirement.
