### ISSUE TITLE
ktest --- error message needs fixing

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#138]
The following error message from ktest needs some polishing:

[Error] Critical: The 'programs' attribute requires a 'extention' attribute: 
                  <test
                  definition=/home/grosu/k-private/tutorial/1_k/4_imp++/lesson
                  _7/exercises/abort/imp.k
                  programs=/home/grosu/k/tutorial/1_k/4_imp++/lesson_7/exercis
                  es/abort/tests/. />
    File: command line
    Location: System file.

1) The English is bad.  a => an, extention => extension.  Would it be possible to put all the error messages in one place, say in a text file indexed in some way, and then have a native English speaker revise them all?

2) The displayed XML is not valid XML.  XML requires you to put the attribute values in quotes, or at least our XML parser does.  Can  we use an off-the-shelf XML pretty printer?

3) I think we agreed that file names are allowed to exceed the 80-character limit.  The splitting to 80 characters above does not look good at all.

**Comment by daejunpark** [comment]
I fixed the first simple typo. And I'll arrange the error messages as you mentioned in the new ktest.

**Comment by traiansf** [comment]
Having all messages in an xml-like format would also allow for opening the
project for internationalization, as volunteers could just translate that
file into their own language and get localized messages :-)

I guess this would be a good project for our refactoring expert Omer :-)

best wishes,
Traian

2013/11/11 Daejun Park notifications@github.com

**Comment by osa1** [comment]
I'm not sure what would be a good way to implement this. I remember using this kind of stuff while writing Android code: http://developer.android.com/guide/topics/resources/string-resource.html this basically allows translators to translate only one file and then all program would be translated. Also, Django people use similar thing: https://docs.djangoproject.com/en/1.6/topics/i18n/ I remember using it years ago, if I remember correctly it uses GNU gettext internally, but I'm not sure.

I'm pretty sure that we have some widely-known designs for this because this is a kind of problem that most software developers should be run into. I'll check that.

**Comment by osa1** [comment]
Current ktest doesn't print any error messages when `programs` is specified but `extension` is not, so there's no way to reproduce this anymore. I think this issue may be opened before rewriting ktest, and new version is not giving an error message for this case. I'll put this error message back.
