### ISSUE TITLE
Make nailgun default?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1387]
I just ran kool-typed-static without and with nailgun.  Without, it took 6'22", which was quite scary, because this is a lot longer than it used to with Maude.  Then I ran it with nailgun enabled and it took 40".  An amazing difference!

Is there any reason not to enable nailgun by default in K?  Also, I found it inconvenient to BOTH start the server AND set the environment variable K_NAILGUN.  This may be neat for developers, but as a user I'd like to not even be aware of naigun; or, in the worst case, to have some commands

kserver start
kserver stop

and nothing else.  Although the question remains: why would a user not use nailgun all the time?

**Comment by dwightguth** [comment]
The reason nailgun is not the default is that it is optimized for the case
where a user is compiling one or more definitions and then running a set of
programs over that definition. Using this workflow, we are able to make K
quite fast, but one thing we lose is that you have to stop and restart the
server if you want to modify the definition and then run programs again. It
is probably possible to write the code in such a way that that cache is
automatically flushed if the definition is recompiled, but it hasn't been a
priority for me to work on because nailgun works and is quite effective the
way it is currently. It is also in particular desirable to separately turn
on the server and enable nailgun because of the case when more than one
server is running on the same machine, which is an important case in user
development. I do intend however to work on an init.d script for the server
which starts it when the RV-match virtual machine boots up and stops it
when it shuts down. That is just something I have not gotten to yet.

**Comment by grosu** [comment]
I want to bring this back into discussion:

> I found it inconvenient to BOTH start the server AND set the environment variable K_NAILGUN.

It is a pain to set an environment variable in Windows, and it seems that if you let the K_NAILGUN set, which is what happens in Windows, then you cannot run K without starting the kserver.  So why do you need the environment variable?  Can't you just check if the server is started?

> one thing we lose is that you have to stop and restart the
> server if you want to modify the definition and then run programs again.

So what happens if you don't do it?  Do you get wrong results, or you don't
get the speed benefits that you get if you stop and then restart it?

**Comment by dwightguth** [comment]
You can actually set environment variables on windows from within the shell, which is how I intended this to be done:

```
> set K_NAILGUN=1
```

That said, I think you are right that we may be able to remove the environment variable and just check whether the server is running. Let me try to work on this in the next couple days and see what comes of it. I will have to test out the fix to see if it causes any problems for workflow, but if everything checks out, we can probably merge such a change sometime next week.

In answer to your other question, you do in fact get wrong results, although usually the wrong results you get will be a crash.
