### ISSUE TITLE
java.lang.UnsupportedOperationException: missing SMTLib translation for isKResult

### ISSUE THREAD

**Issue by McDowell1234** [kframework/k-legacy#1394]
When testing my implementation with ex11.simple to ex17.simple from 2_languages/1_simple/2_typed/2_dynamic/exercises/functions-with-throws/tests/ I was prompted with the error attached.

![bug_ex12 simple](https://cloud.githubusercontent.com/assets/4169957/6589191/257cdd04-c76a-11e4-898f-8099d82eb00d.png)

**Comment by dwightguth** [comment]
Can you tell me whether you get a stuck result that has an unevaluated function term somewhere in it if you rerun the program with the krun flag `--pattrn-matching`?

**Comment by McDowell1234** [comment]
Hi Dwight,

Thank you for getting back to me.

Do you mean --pattern-matching? 

I now get AssertionErrors whenever I run my program regardless of with or without --pattern-matching. 

Any ideas on what is wrong?

![bug_assertionerror](https://cloud.githubusercontent.com/assets/4169957/6601206/5320e142-c7e2-11e4-813f-1bc15fb156bc.png)

**Comment by dwightguth** [comment]
You are the second person who seems to have had a similar issue, but I
still do not have a working program to generate the error. Obviously you
can't post your solution publicly, but can you email it to me at
dwightguth@runtimeverification.com so that I can try to reproduce the issue?

**Comment by dwightguth** [comment]
Er apologies, that is not the correct email address. It should be
dwight.guth@runtimeverification.com. Note the dot.

**Comment by dwightguth** [comment]
Your assertion error is because of the rule on line 397. It is grabbing the entire task cell except the k cell, and copying it into the new task that you are creating. However, you also declare an explicit blockenv cell, so you actually end up with two, causing the error. I will attempt to make the error message slightly better so that this is obvious to other users in the future though.

**Comment by McDowell1234** [comment]
Thank you Dwight,

I fixed the issue, but I am now getting the java.lang.UnsupportedOperationException for ex11.simple to ex17.simple from 2_languages/1_simple/2_typed/2_dynamic/exercises/functions-with-throws/tests/ again as described above. 

I am forwarding you my implementation and would appreciate if you could assist.

**Comment by dwightguth** [comment]
When you run the program with the --pattern-matching flag, you will see that your program is getting stuck because the mkThrows function is not defined for the input you are passing to it. This is because you are trying to use it like a regular construct, matching on it inside the K cell, but functions cannot be used this way. A function can only be matched on itself as a top level construct: ie, it must apply the same regardless of where in the configuration it exists. That said, I don't believe you actually need this construct to be a function, so you can probably just remove the function attribute and have it work.

**Comment by grosu** [comment]
Any chance we can output a nicer error message here?

**Comment by McDowell1234** [comment]
Hi Dwight,

Thanks for your assistance. The program  executes flawlessly through ex10 to ex17 now, but I am sure other users would appreciate if they were shown a more helpful message when this error occurs.

Best,
Michael

**Comment by dwightguth** [comment]
@grosu: I've had some long discussions with Yilong about this issue and the short version as I understand it is that it's not possible for us to have a nicer behavior here until such a time as we can have short-circuit evaluation for #if_#then_#else_#fi, andThenBool, and orElseBool. The best we can do is something that I think probably should be done already which is to make --pattern-matching the default behavior and move the current default under a --symbolic-execution flag.

**Comment by grosu** [comment]
I agree with --pattern-match to be the default!
