### ISSUE TITLE
krun -- better solution display when using --search

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#142]
Currently, the output of krun --search is very hard to test.  People define things differently and then end up having different numbers of states, different orderings of their solutions, and even different numbers of the same solution wrt what one is interested in.

So here is the current output of krun on some example imp++:

```
fslwork$ pwd
/home/grosu/k/tutorial/1_k/4_imp++/lesson_3/tests
fslwork$ krun -d .. ../../lesson_1/tests/div.imp --search
Search results:

Solution 1, State 4:
<T>
    <k>
        .K
    </k>
    <store>
        #symNat(1) |-> 3
        #symNat(2) |-> 2
    </store>
    <env>
        x |-> #symNat(1)
        y |-> #symNat(2)
    </env>
</T>

Solution 2, State 5:
<T>
    <k>
        3 / 0 ~> y = HOLE ;
    </k>
    <store>
        #symNat(1) |-> 3
        #symNat(2) |-> 0
    </store>
    <env>
        x |-> #symNat(1)
        y |-> #symNat(2)
    </env>
</T>

Solution 3, State 7:
<T>
    <k>
        .K
    </k>
    <store>
        #symNat(1) |-> 3
        #symNat(2) |-> 0
    </store>
    <env>
        x |-> #symNat(1)
        y |-> #symNat(2)
    </env>
</T>

Solution 4, State 9:
<T>
    <k>
        .K
    </k>
    <store>
        #symNat(1) |-> 3
        #symNat(2) |-> 3
    </store>
    <env>
        x |-> #symNat(1)
        y |-> #symNat(2)
    </env>
</T>

Solution 5, State 10:
<T>
    <k>
        .K
    </k>
    <store>
        #symNat(1) |-> 3
        #symNat(2) |-> 1
    </store>
    <env>
        x |-> #symNat(1)
        y |-> #symNat(2)
    </env>
</T>
```

The states are completely irrelevant, I think we should just drop them.  If anybody wants to know how many states were generated, then one can use the --statistics option of krun ... which I just noticed that it disappeared.  I think we should have a statistics option, but that is another story.

Also, since different people may get the solutions above in different orders, it would be quite useful to sort them.  To use an option like --sort, which would simply sort the output.  Of course, the drawback of this is that the output can only be displayed after all solutions are calculated.

Further, we can also provide a pattern to krun:

```
fslwork$ krun -d .. ../../lesson_1/tests/div.imp --search --pattern "<k>V:K</k>"
Search results:

Solution 1, State 4:
V:K -->
.K

Solution 2, State 5:
V:K -->
3 / 0 ~> y = HOLE ;

Solution 3, State 7:
V:K -->
.K

Solution 4, State 9:
V:K -->
.K

Solution 5, State 10:
V:K -->
.K
```

This time, besides removing the state information and possibly sorting the solutions, like above, it would be useful to also be possible to maintain only a set of them.  There are really only 2 solutions in what regards the desired variables.  So it would be nice to have an additional option besides --sort, say --set, which removes duplicate solutions.

**Comment by traiansf** [comment]
I guess one could just sort their textual representation, and then it would
be ok to be a set.

best wishes,
Traian

2013/11/11 Grigore Rosu notifications@github.com

**Comment by grosu** [comment]
Well, sometimes people get the same solution more times that others, because they have a different granularity for their interleavings.  You may want to make it such that the number of times the same result in the K cell is obtained is irrelevant.

Grigore

**Comment by ciobaca** [comment]
This issue is an instance of a more general issue that appears often in programming contests, that solutions different from the "official" solution can also be correct.

In programming contests, the solutions of the participants are checked by a so-called verifier program (which is specific to the problem at hand) that takes as input both the official solution and the user's solution and decides if the later is correct.

We should use the same approach here. Rather than modifying the output of krun just for this particular task (other problems could have other requirements), ktest should have the option to pass a verifier program that checks the output. This would be similar to how an external parser is specified for krun.

K should contain a bunch of generic verifiers that ca be used in most situations:
- a dumb verifier that checks strict equality between the outputs
- a verifier that ignores whitespaces
- a verifier that checks equality between subconfigurations specified by an xpath formula

I guess this would solve all the issues that Grigore mentioned, albeit more generically and future-proof.

**Comment by ericmikida** [comment]
I've changed it so that when doing search KRun no longer prints out the state number, and prints out an ordered set of results to address the multiplicity issue Grigore mentioned about. I agree with @ciobaca though, in that this was just a quick fix, and a more general solution implemented in ktest would probably be desirable, and would also address other issues we have already talked about such as whitespace.

**Comment by grosu** [comment]
Eric, while fixing the tests to pass with the new way of displaying the search results, I found that you display empty substitutions like this:

Search results:

Solution 1:Empty subsitution

This is different from how you display non-empty substitutions.  For example, after just removing the state from the previous one I get

Search results:

Solution 1:
Empty substitution

which I think should be the right way to display them.  Besides, "substitution" is misspelled in your new output, which makes lots of tests fail.

**Comment by ericmikida** [comment]
Oops. I'll fix that quick right now.

Eric

On Nov 11, 2013, at 10:45 PM, Grigore Rosu wrote:

Eric, while fixing the tests to pass with the new way of displaying the search results, I found that you display empty substitutions like this:

Search results:

Solution 1:Empty subsitution

This is different from how you display non-empty substitutions. For example, after just removing the state from the previous one I get

Search results:

Solution 1:
Empty substitution

which I think should be the right way to display them. Besides, "substitution" is misspelled in your new output, which makes lots of tests fail.

**Comment by grosu** [comment]
Note that I already modified all the output files, so you only need to modify the implementation.

Grigore
