### ISSUE TITLE
krun crashes when update K without deleting existing kompiled definition

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#145]
```
fslwork$ pwd
/home/grosu/k/tutorial/1_k/5_types/lesson_2
fslwork$ kompile lambda
fslwork$ krun factorial-letrec.lambda 
Exception in thread "main" java.lang.AssertionError
    at org.kframework.kil.TermCons.<init>(TermCons.java:34)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.kil.TermCons.<init>(TermCons.java:39)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.kil.TermCons.<init>(TermCons.java:39)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:68)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:84)
    at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:133)
    at org.kframework.krun.RunProcess.runParser(RunProcess.java:120)
    at org.kframework.krun.RunProcess.runParserOrDie(RunProcess.java:96)
    at org.kframework.krun.Main.execute_Krun(Main.java:1104)
    at org.kframework.main.Main.main(Main.java:59)
fslwork$ rm -r lambda-kompiled/ .k
fslwork$ kompile lambda
fslwork$ krun factorial-letrec.lambda 
<k>
    int
</k>
fslwork$ 
```

**Comment by grosu** [comment]
This is really bad.  It also makes ktest fail on my machine on several programs.  I don't know who's responsible for introducing this new error, but whoever did please fix it asap.  It is quite a strange error.  kompile works fine, but for some reason whatever it generates in the -kompiled folder gets mixed with whatever else was there before, so that krun gets confused.

**Comment by traiansf** [comment]
Perhaps related:

A student in my class got k-nightly.zip from the site, went into
tutorial/2_imp/lesson_4
kompiled
tried to krun
and got a parsing error about something in substitution.k

after removing the -kompiled directory, it worked the second time.

would be interesting to investigate.

2013/11/12 Grigore Rosu notifications@github.com

**Comment by osa1** [comment]
hmm, I thought kompile is supposed to remove old `-kompiled` folder before generating new files .. but apparently it doesn't do that. does doing that solve this problem without introducing other ones?

We're not supporting having multiple backends compiled at the same time, right? (it's not very hard to do though - I think we can simply have subfolders in `-kompiled` for each backend. like `lambda-kompiled/java`, `lambda-kompiled/maude` etc.

**Comment by grosu** [comment]
time the kompilation and you will see that it takes about 50% the time when -kompiled is there.  There is lots of caching going on there, but this time that works against us.  But now I'm confused, too: wasn't .k supposed to keep all the caching?

**Comment by osa1** [comment]
I can trace this error but I'm not sure how to reproduce it.

How do we currently invalidate kompile caches?

**Comment by ciobaca** [comment]
I have also seen a similar (possibly related) error occur in my work. It
happens as follows:

$ kompile --kcells "k1 k2" result --backend symbolic
$ krun ... < arguments skipped for brevity >
Krun was executed with the following arguments:
syntax_module=RESULT
main_module=RESULT
compiled_def=/Users/stefan/work/k/samples/equiv/result-kompiled

Warning: Compiled definition file name (result) and the extension of the
program (minimp) aren't the same. Maybe you should use --syntax-module or
--main-module options of krun
Warning: Maude produced warnings or errors.
libc++abi.dylib: terminate called throwing an exception

$ rm -rf result-kompiled/
$ kompile --kcells "k1 k2" result --backend symbolic
$ krun ... < arguments skipped for brevity >

Now everything works as expected.

Cheers,
Stefan

On Tue, Nov 12, 2013 at 7:16 PM, Ömer Sinan Ağacan <notifications@github.com

**Comment by ericmikida** [comment]
To answer @osa1 about multiple backends, right now it does seem to support having multiple backends kompiled at once although that seems buggy. 

If I kompile the simple language in the samples/java_rewrite_engine directory for the java backend then for the maude backend, I can krun --backend=maude just fine, but krun --backend=java crashes with a weird error.

If I kompile the maude backend first, and the java backend second, then both backends run fine with krun. I don't know if this should be a separate issue or if it is related to this one. Either way it seems that kompile isn't quite cleaning up after itself correctly in all cases.

**Comment by osa1** [comment]
Having different folders for backends would simplify our job. And for shared files(like SDF tables etc.) we can use top level folder.

Like:

```
.
└── lambda-kompiled
    ├── java_backend (directory)
    ├── maude_backend (directory)
    └── sdf_files (file)
```

and then when compiling for a backend, compiler would remove `x_backend` folder, then by checking version number in root folder, either removes sdf files and other backend files too or just reuse them.

I guess as version number we can use git revision number.

**Comment by ericmikida** [comment]
Oops...actually I just checked again. When kompiling maude backend first, followed by java backend, krun --backend=maude doens't throw an error, but it doesn't actually do any rewriting either. So no, we don't support having multiple backends kompiled at once, but that doesn't seem to be reflected by error messages. Something still isn't getting cleaned up properly though because I would think krun should throw the error related to an uncompiled backend, rather than running anyways and giving weird errors or no errors at all.

On a side note, I like the suggestion made by @osa1 because I often would like to use both compiled definitions without constantly recompiling for each backend.

**Comment by grosu** [comment]
Omer and others, can you please look into this error?  This is a recent one, so whoever made recent changes to the code must have introduced it.

**Comment by osa1** [comment]
Is this bug new or is it just discovered/reported recently? I'm currently trying to trace the problem and it looked to me that this bug were there for long time. As far as I can understand:
- we're not checking for version numbers or other information while loading already compiled definitions, so any changes on kompile/krun should cause this problem.
- `.k` folder is not used at all. I'm watching that folder using a filesystem watcher tool and it's definitely not used. I guess we did this to prevent data races or other problems cause by concurrency in kompile processes spawned by ktest.

**Comment by osa1** [comment]
To be more precise, `.k` is not used during kompile but it's still generated. It's used by krun for maude backend.

**Comment by osa1** [comment]
I'm still collecting information about that mysterious .k folder. Here's more info:
- `kompile` was creating `.k` but was never using it. I removed that code.
- Java backend creates .k but never uses it. I'm removing that code shortly.
- `*-kompiled` folder may be holding redundant files. For example, `kompile-options.bin` file is created only to read one variable, `sort-cells`. And that variable is never set `true`, so it's not necessary. I removed that file, and `sort-cells` is always `false` right now. I didn't push this change, please tell me if you need that functionality and explain me how you were using that(because currently there is no way to set that variable) otherwise I'll remove that variable completely.

**Comment by traiansf** [comment]
Beware though that your recent push made all tests failed (see Jenkins).

2013/11/14 Ömer Sinan Ağacan notifications@github.com

**Comment by traiansf** [comment]
We have a compiler pass we experimented with which would allow to structure
the cells more than they are right now.
The sort-cells variable was used to inform krun that that phase was applied
during compilation, because the configuration needed to be initialized
differently in this case.

Currently we're not using it though, so feel free to do whatever you want
with it;  however I believe that kompile-options.bin could be used to
inform krun about the backend used to kompile, so that one does not need to
pass the backend to krun, as Grigore mentioned in a parallel issue.

Traian

2013/11/14 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
> Beware though that your recent push made all tests failed (see Jenkins).

are you sure? it works fine on my fsl machine. could it be related with your changes?

**Comment by grosu** [comment]
It failed right after your push, Omer.  Whenever Jenkins fails after your push, you should check the jenkins report to see exactly why it failed and fix it or otherwise revert your changes.  I know it is exciting to move on to new stuff and not look back, but the master must not be broken, no matter what.

Grigore

**Comment by osa1** [comment]
This is very bad. Pdf backend does really strange things. It generates same files that we already have in `*-kompiled` folder, but in `.k` folder. And it doesn't create `.k` folder, it just assumes it's there. I'll send a mail to mailing list for further discussions about this.
