### ISSUE TITLE
Non 7-bit ASCII chars in .k files result in exception

### ISSUE THREAD

**Issue by jthywiss** [kframework/k-legacy#1456]
When a .k input file contains a terminal ("-delimited) with non 7-bit ASCII chars, and is kompiled, an exception is thrown:

```
[Error] Internal: Uncaught exception thrown of type IllegalArgumentException.
```

K Version 3.5.1 on Mac OS X 10.9.5

**Comment by dwightguth** [comment]
Can you please provide me with the exact string that you wish to place inside the terminal? I tested this with one of the characters in the LATIN-1 encoding, and it seems that SDF, the parser we use internally, may not support enough of the non-ASCII character set for this to be possible at the current time. However, I can try again if I have the exact string you are interested in, and see if that makes any difference.

That said, we are currently in the process of replacing the entire parser frontend with a new infrastructure, and the new infrastructure should support the full generality of Java's UTF-16 encoding. If you want, I can try to update this issue for you when the new version drops.

**Comment by jthywiss** [comment]
I used Unicode U+2022: BULLET

**Comment by dwightguth** [comment]
Unfortunately, due to the limitations of SDF, I don't believe it will be possible for you to work around this issue in K 3.5. However, I have fixed a bug in the latest version of K which should provide you with limited functionality if you choose to avail yourself of it. You will still not be able to use unicode characters in K definitions, but if you want to use them in the syntax of your programs, it should be possible if you use the latest version of K, and invoke krun with the flags `--parser "kast --parser newprogram"`. You may have to modify your definition slightly if you are making use of lexical syntax productions in it, because what this command does is enable the new parser for use in programs that will be used in K 4.0. I can walk you through this process if it is necessary.

Note that because you cannot use unicode characters in K definitions, even with this approach, you will have to define an alternate syntax for the productions, using the same KLabel, in order to allow yourself to write rules dealing with this production.

Full support for unicode will be present in K 4.0, which we are hoping we will be able to release sometime this summer.

Please let me know if you have further questions.

**Comment by jthywiss** [comment]
Easy enough for me to work around using ASCII-only terminals for now.  Mainly the bug, from my point of view, was an exception rather than a comprehensible error message.

**Comment by dwightguth** [comment]
Okay. I am going to close this since it seems like you have your situation resolved, and we have solved the problem going forward. Please feel free to reopen if you need anything else.
