### ISSUE TITLE
krun --- java backend sends output to stdout during search

### ISSUE THREAD

**Issue by ericmikida** [kframework/k-legacy#146]
If you do search on a program with output, the maude backend doesn't do any io and the <out> cell is preserved at the end of the search. This doesn't happen with the java backend, and you end up with a ton of extra output and empty <out> cell upon termination.

To reproduce:

samples/java_rewrite_engine/simple/untyped$ kompile --backend=java simple-untyped.k

samples/java_rewrite_engine/simple/untyped$ krun --search --backend=java holzmann/unthreaded.simple

Since there is only one state, the output looks normal, but shouldn't be there. If you run one_put_one_get.simple, you'll see that the output is replicated a ton of times as well.

**Comment by yilongli** [comment]
@dwightguth @andreistefanescu I would like to use some help here. Essentially, when we are doing searching, `K.io` is set to false, then `#noIO` will be placed before `#istream(_)` and after `#ostream(_)` in input cell and output cell respectively, which later cause `#istream(_)` & `#ostream(_)` to be resolved according to the last two rules in `io.k`. Ideally, a `$noIO` should be plugged into the configuration term during kompilation; then during krun,  `krun.Main#makeConfiguration` and `krun.Main#plug` will construct the `#noIO` term and substitute `$noIO` with it. Right now, the problem is that `$noIO` is not correctly plugged  into the configuration term before it's serialized and stored. I am not familiar with this process, so I couldn't find the right place to modify it. Other than that, it should be a simple fix.

**Comment by yilongli** [comment]
Never mind, I kind of understand what to fix.
