### ISSUE TITLE
Should `krun` without arguments execute `krun --help`?

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1482]

**Comment by radumereuta** [comment]
No, it should execute the definition. This means the definition doesn't necessarily require input, and it would be just like a program.

**Comment by cos** [comment]
most command line tools display help with run without arguments.

while it is possible to execute a definition without arguments, in the vast majority of cases it needs at least a program input -- I think it is an error not to have one now

also, what happens when I have multiple definitions in the same folder?

**Comment by radumereuta** [comment]
- I need a way to run my quine example. The way I do it now, is to `kompile quine.k` and then `krun`. For a program to be a quine, it must take no input. Also we would like K to be used like a programming language. I think @grosu had something like this in the sudoku example.
- It is an error for `kompile`, because it doesn't have a meaning, but for `krun` we do have one (see above). In any case, if a user forgets to give a command line argument even though one was expected, right now it gets an error message, saying that `$PGM` was not initialized. But I repeat, if the `configuration` doesn't have a variable `$PGM`, `krun` shouldn't take a default argument.
- If you have multiple compiled definitions in the same folder, then krun should complain, and it does right now. The user should specify which folder wants to use.

**Comment by cos** [comment]
yes, Radu, but user interfaces, including command line ones, should favor the common case

**Comment by radumereuta** [comment]
And what I was saying is that this is not the common case you are talking about. It's more like `ls` from linux.

**Comment by cos** [comment]
what is quine?

**Comment by radumereuta** [comment]
http://en.wikipedia.org/wiki/Quine_%28computing%29

**Comment by cos** [comment]
so quite and sudoko are our common cases?

**Comment by radumereuta** [comment]
And what I was saying is that this is `not` the common case you are talking about. It's more like `ls` from linux.

**Comment by dwightguth** [comment]
The question ultimately is whether or not we want to create a deliberate anomaly in the command line interface to krun, simply for the sake of making it easier for users to view help for the first time. Personally I think that this is a bad idea. By no means do all command line tools provide a help message when invoked with no arguments. GCC does not, for one. It will be quite confusing to explain to users that they have to type in some special flag just to make krun execute with no configuration variables, when it otherwise quite consistently executes with exactly the configuration parameters specified on the command line. In general my feeling is that if a tool can successfully execute and provide a meaningful result with no command line arguments, it makes little sense to deliberately disable that case in order to try to conform to some standard that not all unix processes even conform to.

**Comment by cos** [comment]
one option is to have it display help when it doesn't have a definition available, or the definition requires an input. in any case, it is not a big issue.
