### ISSUE TITLE
ktest --- home directory "~" unrecognized

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#152]
```
fslwork$ pwd
/home/grosu/k-private/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived
fslwork$ more config.xml
<tests>

  <include file="~/k/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived/tests/c
onfig.xml" />

</tests>
fslwork$ ktest config.xml
Buildfile: config.xml
[Error] Critical: The configuration file does not exists.
    File:
/home/grosu/k-private/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived/~/k/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived/tests/config.xml
    Location: System file.

fslwork$ 
```

**Comment by traiansf** [comment]
I'm not sure it should be...

~ is specific to bash and it is expanded by it.  Using ~ might make no sense for windows users, which would maybe think of using %HOME% ...

Moreover this is not portable when switching to another user

**Comment by grosu** [comment]
Maybe not ~, but we need something similar or otherwise some intelligent replacement to account for the fact that many definitions that we want to test may not be under the k main foder.  For example, the solutions to the K exercises are in a different folder.  In my setting, it happens to be at the same top-level as k, which justifies me to write my config.xml file as shown above.

On the other hand, I would not mind dropping ~, that is, to just write 

```
 <include file="k/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived/tests/c
onfig.xml" />
```

but in that case we need a way to redirect the root folder of the included file attributes.

Maybe we need a new option, something like "ktest --include path config.xml", where
path is prepended to all the paths that appear in include attributes in config.xml?  This seems to be
cleaner than what I originally proposed and also more powerful.

**Comment by grosu** [comment]
Daejun or Omer, can you please take care of this?  It is needed in order to test the exercises, which are in a totally different directory.

**Comment by daejunpark** [comment]
@grosu Okay, I see. But, I have a question. What if we have two different include's: one of them is just a normal include, and the other is from a totally different directory? In that case, we need a way to apply the '--include' option to only the latter.

Can I suggest another proposal? We can use a user defined variable such as '$DIR' and set its value using a command line option like '--set DIR=/another/root/path'. And then, we can just specify like this:

```
<include file="$DIR/config.xml" />
```

And, we can just stay with the same rule: all included paths are interpreted as being relative to '$DIR'.

---

That being said, I want to clarify your proposal.

For example, let command line argument of ktest be:

```
  $ ktest C/config.xml --include X --directory D --programs P --results R
```

and configuration file 'C/config.xml' be:

```
  C/config.xml:

  <include
    file=C1/config1.xml
  />
```

then 'X/C1/config1.xml' should be included. (Am I right?) Let it be:

```
  X/C1/config1.xml:

  <test
    definition="D1/lang.k"
    programs="P1 P2"
    results="R1 R2"
  />
```

then the paths should be eventually resolved as follows (right?):

```
  <test
    definition="D/X/D1/lang.k"
    programs="P/X/C1/P1 P/X/C1/P2"
    results="R/X/C1/R1 R/X/C1/R2"
  />
```

Also, for another example, let command line argument of ktest be:

```
  $ ktest C/config.xml --include X --directory D --programs P --results R
```

and configuration file 'C/config.xml' be:

```
  C/config.xml:

  <include
    file=C1/config1.xml
    directory=D0
    programs=P0
    results=R0
  />
```

then 'X/C1/config1.xml' should be included. (Am I right?) Let it be:

```
  X/C1/config1.xml:

  <test
    definition="D1/lang.k"
    programs="P1 P2"
    results="R1 R2"
  />
```

then the paths should be eventually resolved as follows (right?):

```
  <test
    definition="D/X/D0/D1/lang.k"
    programs="P/X/P0/P1 P/X/P0/P2"
    results="R/X/R0/R1 R/X/R0/R2"
  />
```

**Comment by daejunpark** [comment]
@grosu  @dlucanu 
And my proposal also might be a solution for Dorel's case:

---

On Nov 16, 2013, at 10:01 PM, Daejun Park dpark69@illinois.edu wrote:

Hi Dorel,

Sorry for the late reply.

The reason of the failure is the krun option --ltlmc: its value is a relative path which is not properly resolved after included.

For example, the following element specify the value "programs/form-threads.cink", which makes sense only at the directory 'cink-semantics/ltlmc' not under the 'cink-semantics'.

```
  <program name="threads.cink">
    <krun-option name="-ltlmc" value="programs/form-threads.cink" />
  </program>
```

That is, if you run ktest at the top of 'cink-semantics', then it virtually executes krun as follows: (As you can see, the value of '--ltlmc' is not correct.)

$ cd cink-semantics
$ krun ltlmc/programs/threads.cink -ltlmc programs/form-threads.cink 

FYI, the 'include' feature does not mean that ktest changes the working directory. It just creates a new flattened config.xml file including others. Of course, all relative paths are resolved during inclusion, but unfortunately the values of options are not the case. This is because we do not look into the options'  values and just consider it as a black-box.

We need to think about how to deal with such a case.
I'm sorry for not being much helpful to you at this moment.

Best regards,
Daejun

On Nov 14, 2013, at 2:55 AM, Dorel Lucanu dlucanu@info.uaic.ro wrote:

Dear Daejun,

Thanks for your rapid answer.
That strange behavior (nonterminating on ltlmc/programs) happens only on my Mac machine.
I testet it on our fmse machine (Linux) and indeed it works.

Now I have a different problem. I reorganized the config.xml files: each folder has its own config file and the config from the root includes the other ones.
When I run config.xml from cink-semantics/ltlmc it works fine.
When I run config.xml from cink-semantics (that includes the previous one) it fails (see https://fmse.info.uaic.ro/jenkins/job/cink-semantics/222/console).

I used "-v" option but I didn't see why it fails (is it possible to display the krun kommand when the option "-v" is used?)

Thanks again.
Dorel

**Comment by grosu** [comment]
I like your proposal, Daejun!  But I think you can keep it even simpler, by letting people simply use whatever environment variables they want, instead of introducing the --set option.  For example, in my case, I would just write 

```
  <include file="$HOME/k/tutorial/1_k/1_lambda/lesson_8/exercises/mu-derived/tests/config.xml" />
```

If somebody wants

```
<include file="$DIR/config.xml" />
```

then they can use their shell or whatever they use to set the variable $DIR to whatever folder they want.

**Comment by daejunpark** [comment]
Oh, sounds great! That would be better. I'll do so. Thanks!

**Comment by daejunpark** [comment]
Done: 4c874f782341a9ec7968af60adc092a13bb97274
