### ISSUE TITLE
ktest --- better error message needed when paths are incorrect

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#156]
Each time I foget about the --programs "." thing I get an error message which doesn't help me at all:

```
fslwork$ ktest tests/config.xml 
Buildfile: tests/config.xml
[Error] Critical: Does not exist or not a directory:
/home/grosu/k/tests/tutorial/1_k/tests
    File: 
    Location: 
```

Instead, it should be something like this:

```
fslwork$ ktest tests/config.xml 
Buildfile: tests/config.xml
[Error] Critical: The following program directory does not exist:
/home/grosu/k/tests/tutorial/1_k/tests
    File: path/to/respective/included/config-file
    Location: corresponding line number
```

**Comment by osa1** [comment]
This is very easy to do, except our current XML parser(DOM based XML parser in from standard Java distribution) does not track position information. I made some research on this and I found that our options are either
1. Find an external library that shares same API with Java DOM parser(so that we can replace the library with minimal effort) but also tracks position information.
2. Use Java SAX parser, which keeps track of position information (there are some debate on how precise it is, though) http://docs.oracle.com/javase/7/docs/api/org/xml/sax/Locator.html

I think I'll go with `2`.

**Comment by osa1** [comment]
I implemented this in new ktest. Example:

```
[Error] Critical: definition file
/Volumes/dev/k/tutorial/1_k/1_lambda/lesson_1/lambda.k is not a file.
        File: file:///home/omer/K/k_new_dist/k/tests/config.xml.xml
        Location: [line 7:71 to line 12:10]
```

@daejunpark Now all we need is to replace old ktest with new ktest :-)

**Comment by radumereuta** [comment]
I like how the Location information looks. Do you think you can implement it for all the other tools?
I shouldn't be that hard, considering that we have only one class that prints such error messages. We still want to keep the internal representation as (a,b,c,d), but it would be much clearer for users if we print it like the above.

**Comment by osa1** [comment]
@radumereuta I'm not sure in what case you'd like to print location information, but generally to be able to do that you need to annotate intermediate representation nodes with location information(or use some kind of table to map nodes to location information. I personally don't like this method). For example, in this case, I'm annotating XML nodes with location information, so that when error happens I could get location information from XML node's annotation.

(I think this is a widely used pattern, in Haskell we generally define AST nodes like this:

```
data Node a = Node1 a ...
            | Node2 a ..
```

etc. where `a` is annotation type(this type is polymorphic). There are also other methods to do same thing, each one with it's advantages and disadvantages, this blog post surveys other methods http://blog.ezyang.com/2013/05/the-ast-typing-problem/ )

**Comment by osa1** [comment]
Implemented in new ktest:

```
➜  k git:(master) ✗ ktest tests/config.xml 
[Error] Critical: program directory
/home/omer/K/k_new_dist/k/tests/tests/examples/quine-explicit is not a
directory.
        File: file:///home/omer/K/k_new_dist/k/tests/config.xml
        Location: [line 30:26 to line 35:10]
```
