### ISSUE TITLE
Some tutorials don't compile

### ISSUE THREAD

**Issue by egonelbre** [kframework/k-legacy#1560]
I started experimenting with K framework and found that some of the tutorials don't compile.

I'm using Version 3.5.2 downloaded from https://github.com/kframework/k/releases on Windows 7.

```
> cd tutorial\1_k\1_lambda\lesson_2
> kompile lambda.k
[Error] Critical: Found two modules with the same name: SUBSTITUTION
        Source: File: C:\Programs\K\include\modules\substitution.k
        Location: (158,1,298,9)
```

```
> cd tutorial\1_k\5_types\lesson_9.5
> kompile lambda.k
[Error] Critical: Found two modules with the same name: SUBSTITUTION
        Source: File: C:\Programs\K\include\modules\substitution.k
        Location: (158,1,298,9)
```

Probably would be easy to have a script that tries to compile all the samples/tutorials and see which ones fail.

**Comment by dwightguth** [comment]
@grosu we added a note to the readme about this, but people keep getting tripped up. I think we need to release a K 3.6 so that people who just try out K by downloading the latest release and then running the tutorial don't run into this problem. I still want to release a K 4.0 when we finish the KORE translation, but we should probably do a short term fix in case that doesn't happen for a while yet.

**Comment by dwightguth** [comment]
@egonelbre in response to your question, we kind of screwed up the tutorial in this release because it was part of our transition away from using Maude internally, and so you actually have to specify an extra option to get it to work. You can run `kompile --backend java lambda.k` or you can download the unstable version if you'd rather, which should be just as functional, and actually performs faster on many examples.

**Comment by egonelbre** [comment]
@dwightguth sure, these things happen occasionally :). Thanks for the tip.

**Comment by grosu** [comment]
Is there any reason to not release 3.6? Any drawback that you an think of?  @dwightguth , @cos , @andreistefanescu ?  If not, then I think we should release 3.6 asap.

**Comment by andreistefanescu** [comment]
We should release 3.6.

**Comment by grosu** [comment]
Since nobody complained,  let's release.

@dwightguth can you please release?
@pdaian can you please make sure that kweb also works?

**Comment by cos** [comment]
I think we can close this issue.
