### ISSUE TITLE
update Nailgun to include my patch

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1610]
I recently fixed the races reported by RV-Predict inside Nailgun: https://github.com/martylamb/nailgun/pull/67

@dwightguth can you please update your Nailgun fork to include my patch and deploy this race-free version?

**Comment by grosu** [comment]
@yilongli , many thanks for doing this!!!  @dwightguth , can you please let us know if these fixes significantly affect the performance of K?

Guys, we need to write a nice blog about this experiment on using RV-Predict on K.  To me, an interesting thing that it shows is that people should use RV-Predict from early stages in their project and continuously, so that they fix the races as they occur in their code.  If you only use it at the end and see tens of races, you feel demoralized as a developer to spend hours and hours to fix all of them, so you end up only fixing those that gave you non-deterministic bugs in the past.

**Comment by grosu** [comment]
Also, an extra-additional benefit, if one can say so, is that using RV-Predict continuously as you develop and test your software, enables you _learn_ and _understand_ concurrency better than before, which is in itself a plus.  @yilongli, when we write our blog, or even on RV-Predict's page/documentation, let's make sure we add these under "Why should I use RV-PRedict" or/and under "When should I use RV-Predict".

**Comment by grosu** [comment]
@yilongli, it is really nice that you fixed the bug in nailgun, too, on your way of fixing K!  Please add this to the blog, too, namely that races are often in off-the-shelf components that people use in their applications, even in ones that have been used for some time and by many.  Fixing bugs in those is actually even more important, because of that.

**Comment by yilongli** [comment]
@grosu OK, I have put them on my TODO list. I have fixed most of the simple race reports in K, but there are some more fundamental and complex changes which I would rather leave to the K developers. For example, [this one](https://github.com/kframework/k/issues/1606). Once @dwightguth fixes them, I can start write up the blog post about using RV-Predict on K.

**Comment by grosu** [comment]
@yilongli Thanks!

In fact, I believe that you/we should write an experience report paper explaining your experience with finding races using existing systems, including RV-Predict.  We can talk about that on hangouts if you are interested.  I think such a paper would be very nice and could have a large impact.
