### ISSUE TITLE
Pdf backend freezes on windows

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#162]
This seems to only be occurring on windows systems, but what basically happens is that kompile freezes waiting for pdflatex to return and pdflatex does not return for some strange reason.

However, the generated latex files compile just fine.

I bisected this using git bisect and found that 1d397f800a0a7d5f0f70a7e50cf7036999b77e17 is the first bad commit
Author: osa1 
Date:   Fri Nov 15 12:40:33 2013 +0200

```
some other improvements in pdf backend
```

Omer, could you please take a look into this.  I think you changed how the main process waits for the spawned process to finish, but apparently did it in a way that confuses Windows.

**Comment by osa1** [comment]
Interesting. What I did in this commit is this: In PDF backend there's a meaningless code that basically reads output stream of pdflatex without doing anything with the output. What's more strange is that it does it two times(basically same code duplicated one more time).

But now I think it may be a hack to make it working on Windows. Either way, I think there should be a better solution than adding meaningless hacks to code.

Unfortunately I don't have windows system and I don't know how to test it. Any ideas on this? Can anyone provide me SSH access or whatever on a Windows system to let me test and find a solution to this?

**Comment by traiansf** [comment]
I think this might help as to understanding why...
http://stackoverflow.com/questions/5483830/process-waitfor-never-returns

2013/11/18 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
Yeah, that link and this one
http://stackoverflow.com/tags/runtime.exec/info really
helped me to understand it. Looks like Java does not provide uniform API
for processes, because you don't need to consume output streams on Linux.
I'll add required code back and add some comments too (so that someone like
me won't remove that code in the future).

---

Ömer Sinan Aðacan
http://osa1.net

2013/11/18 traiansf notifications@github.com

**Comment by osa1** [comment]
The problem is, I'm not sure how much do I need to add. Does simply consuming output stream makes it work on Windows? Because I can't test it. Also, this lead me to suspicion, I think new ktest may not work on Windows at all, because I didn't take this kinds of weird behaviors into account. I need to read more about this in Java manuals.

@daejunpark do you have any ideas on this? I think you're the one who added `StreamGobbler` and similar stuff to ktest while we're righting with concurrency bugs, so you might have more experienced than I have.

**Comment by osa1** [comment]
@traiansf can you please try again on Windows? I'm currently consuming program output, it that's enough it should be working now. In that case I'll add some comments to that code(so that a reader like me from future won't delete that parts) and close this issue.

**Comment by traiansf** [comment]
Thanks! That seems to do the trick.  It now works as expected.  Feel free
to close this issue.

2013/11/20 Ömer Sinan Ağacan notifications@github.com
