### ISSUE TITLE
latex backend: special characters are not escaped

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#165]
Test definition:

module TEST
//@ Needs escaping in latex: %
endmodule

Run with:

kompile -v --backend pdf --doc-style "style=math" test

Special latex characters from comments, line %, have to be escaped. Spent an hour today debugging a problem like this.

**Comment by traiansf** [comment]
Not so sure about that.

Whatever you write on a LaTeX comment line is LaTeX code.  I wouldn't
special case %
People using the documentation feature need to be familiar enough with
LaTeX, anyway.

If % would appear outside LaTeX comments, then I believe it would be
escaped.

2013/11/20 denis-bogdanas notifications@github.com

**Comment by denis-bogdanas** [comment]
Yes, I realize that sometime we need to use special latex characters in comments unescaped. Like \begin{itemize}, \item. Maybe we can have two types of comments - escaped and unescaped. 
Something like:
  \\@ - unescaped, used when comments contain special latex commands like \item
  \\$ - escaped, when documentation contains plain text, and we don't want to worry about latex compatibility. Requires minimal knowledge/awareness of latex backend. 

Anyway, this subject is worth to be open for brainstorming. Grigore, what is your opinion on that?

**Comment by grosu** [comment]
I am not sure I understand the problem very well.  So you want the lines with % to be, or not to be comments in annotated documentation like

/*@ abc
% def
ghi */

I think the above should simply cut and paste what's in between /@\* and */ and send it to Latex as is, where %def will be interpreted as a Latex comment.  That's what I would expect from the tool.  What exactly did you spend 1 hour with?

**Comment by denis-bogdanas** [comment]
Why I propose to have 2 types of comments, annotated and not annotated?

Because I want to have comments that both look nice in the .k source code and produce nice latex, whenever possible. If I want to use a latex special character in comments, I don't want to escape it like \%, it don't look nice anymore. I don't want to see in k comments statements like "Performace increased by 5\%." Moreover it is easy to forget to annotate such characters. Now if latex backend would know to annotate such characters automatically, then we would have the same text in latex as in comments.

However, this approach is not applicable in all cases. Sometimes we want to add specific latex formatting in our comments, like \begin{itemize} \item \end{itemize}. In this cases we need a different latex comment marker, to instruct latex not to annotate special characters.

Why I spent one hour? Well just try the example I wrote on the beginning of the topic. Looks like latex backend put % on the same line with the code generated for endmodule, and broken the latex document.

**Comment by grosu** [comment]
I still don't understand very well your problem.  What I understand is that you found a bug, namely that the latex backend should put a newline after each Latex comment.  This should be fixed, which is why I just labeled this issue as a bug.  But in what regards // vs //@ vs //$, I think we would make it too complicated to have three different kinds of comments, and even more error-prone than it is now.  For example, it would be highly non-trivial to convert space formatting automatically to Latex.  If you want to convert things adliteram to Latex, you can use for example the verbatim model all the time.  For example:

/*@ \begin{verbatim}
Performance increased by 5%, and

  \LaTeX

does not care about it, it does not even take its name as a command above.

   And keeps my spacing, too.  %
\end{verbatim} */

**Comment by denis-bogdanas** [comment]
I agree, verbatim would do just what you suggested. The new type of commend would be just a shortcut for verbatim. As for the bug that you described, I opened a new issue for it, to keep the things clean:

https://github.com/kframework/k/issues/171

Closing this issue with wontfix.
