### ISSUE TITLE
Rule auditing should report sorts on match failure

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1679]
Trying to fix up imp++ in kore, I had a failed rule application which was reporting that some term coluldn't unify against a variable `S:Block`, but the term was built from a label which was only declared in Block. It turns out by debugging that the object was assigned sort KItem because some terms inside of it had the wrong sorts. It would be useful to provide more information about why the term had the wrong sort.

**Comment by dwightguth** [comment]
This is actually pretty tricky. The computeSort algorithm may not necessarily ever run during the audit itself; the term may have already had its sort computed by that point. I think the ideal solution would be to annotate all the subterms in the term being printed with their sort. It shouldn't be too terribly hard to implement, but I have no idea when I will get to it because it's not at all high priority from the perspective of the company at the moment.

**Comment by bmmoore** [comment]
Can't you report the sort information the Java backend keeps about its terms?

**Comment by dwightguth** [comment]
Yeah I mean, that's what I meant.
