### ISSUE TITLE
#symInt(n) not parsed correctly by ground parser

### ISSUE THREAD

**Issue by ciobaca** [kframework/k-legacy#168]
Consider the language:

stefan.ciobaca@fmse:~/work/k$ cat test1.k
module TEST1

syntax Exp ::= Int
             | Exp "+" Exp [strict]

configuration <k> $PGM:Exp </k>

rule I1:Int + I2:Int => I1 +Int I2

endmodule

And the program:

stefan.ciobaca@fmse:~/work/k$ cat p2.test1
# symInt(1) + #symInt(2)

krun p2.test1 --parser "kast -groundParser"

produces ambiguities like:

[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1:
   #symInt
2: KLabel ::= "#" K

(The regular parser works fine).

I don't know how to prefer one over the other (that is, to prefer #symInt to "#" K).

This bug makes it impossible to use the symbolic backend to verify programs. It seems that the first commit that introduced this problem was https://github.com/kframework/k/commit/da32e8a8f155561b69573112960be48df51663be), so I'm assigning the bug to Traian.

**Comment by radumereuta** [comment]
Fixed in revision f3a133f97ebef8c1da75b75838aad6b0967821da

Which reminds me. Should the symbolic stuff be available all the time? Right now I'm generating at runtime all the predicates necessary for parsing stuff like isSymbolicXXX, #symXXX.

I suggest that we generate such things in a module, say SYMBOLIC-SYNTAX, and only include it in definitions that we want to work with symbolic stuff. This will take a bit of strain from the parser, and could reduce the compilation time noticeable.

I'm expecting everybody to weigh in on this issue. Especially the guys that use symbolic stuff. Would it be too much of an inconvenient for you guys?

**Comment by traiansf** [comment]
Unfortunately, symbolic stuff is used quite frequently in the K tutorial. e.g., whenever you ask for a fresh something.

**Comment by dlucanu** [comment]
Symbolic stuff is a part of K, not an optional feature. As Traian said, it is used in the language definitions. Sorry for you Radu, no alternatives.

**Comment by radumereuta** [comment]
I'm not the one that has to kompile definitions over and over, so I'm not the one that suffers the most.
I was just trying to make things more efficient.

I guess I will close this issue for now.
