### ISSUE TITLE
cell fragment parsing issue

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1747]
For a rule that matches a cell fragment:

```
configuration <T> 
  <k> $PGM:K </k>
  <x> 
    <a> .K </a>
    <b> .K </b>
    <c> .K </c>
  </x>
</T>

syntax KItem ::= frag(XCellFragment)

rule frag(<x>-fragment `<a> A </a>` noBCell noCCell </x>-fragment) => .K
```

It generates a parsing error:

```
$ kompile --kore
[Error] Compiler: Had 1 parsing errors.
[Error] Critical: Unexpected sort Cell for term
<a>(#noDots(),#token(#KVariable,"A"),#noDots()). Expected ACellOpt.
```

@bmmoore Do you have any idea?

**Comment by daejunpark** [comment]
The problem is that `<a> A </a>` should be of `ACell`, but is inferred as just `Cell`.

Sort casting is an workaround:

```
`<a> A </a>`:>ACell
```

Is there any better way?

**Comment by daejunpark** [comment]
see also #1744

**Comment by daejunpark** [comment]
see also #1748

**Comment by bmmoore** [comment]
I think this is just a little problem with how the concrete syntax for cells in rules is generated.
The actual labels of the cells are defined by productions as described on the KAST and KORE wiki page, but to allow configuration abstraction in the full K syntax we generate a looser grammar using a generic `Cell` sort. I think the problem is just that we are declaring the syntax of specific cells with one production like `syntax Cell ::= "<a>" Cells "</a>"` rather than making two production like `syntax ACell ::= "<a>" Cells "</a>"` and `syntax Cell ::= ACell`.

I've worked on that code before, if I'm right about the cause this should be a quick fix.

**Comment by bmmoore** [comment]
@daejunpark Has this been fixed?

**Comment by daejunpark** [comment]
yes.
