### ISSUE TITLE
Execution backend available in kernel

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1758]
Despite extensive talks about this, there is still no backend available in the `kernel` module. In consequence, there is no way to expand macros during compilation. The easiest thing now would be to simply make the `kernel` depend on the `java-backend` somehow.

**Comment by dwightguth** [comment]
Honestly, the actual macro expansion itself is quite basic. I think it should be possible to write a simple macro expansion pass that operates over KORE. It would collect the macro klabels in the definition, map them to macro rules, and then iterate through the rules and terms and try them until it reaches a fixed point. This is basically all the Java backend is doing anyway, and it doesn't actually involve too much code. It doesn't even need to be that fast because you can in theory run it only once for any given definition and program. I can put this on my list of things to do, but I have no idea when I'll get to it. It's not really a high priority for me since for the most part having the OCAML backend depend on the Java backend works just fine. Maybe you would be better off assigning this to someone else? I don't really like the idea of making the kernel depend on the java backend. They're both part of the distribution, so if you want a backend to use the java backend's macro expansion, you can just add it as a dependency. Really the benefit to having one as part of the kernel would be to break the dependency on the Java backend for other backends.
