### ISSUE TITLE
Token regex

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#1812]
I want to parse a bracket free string as a token. I use the following production:

```
syntax NoBracket ::= Token{[^\{\}]*} [onlyLabel]
```

But I get the following error:

```
[Error] Inner Parser: Lexical error at line 8, column 37.  Encountered: "^"
```

How should I change the regex to get what I described above?

**Comment by radumereuta** [comment]
Try using the new parser. You will have to say something like this:

```
syntax NoBracket ::= r"[^\{\}]+" [token]
```

You can find more information about how to specify the syntax [here](https://github.com/kframework/k/wiki/Syntax-specification-for-the-new-parser). Also, you can find a few more examples on how to use them in real life in [e-kore.k](https://github.com/kframework/k/blob/master/k-distribution/include/builtin/e-kore.k) and [kast.k](https://github.com/kframework/k/blob/master/k-distribution/include/builtin/kast.k).

Please let me know if this was helpful so I can close this issue.

**Comment by laurayuwen** [comment]
@radumereuta So in order to parse java programs, I should also make changes to syntax according to the wiki you suggested here, right?

**Comment by radumereuta** [comment]
If you want to use the new parser, then yes.

**Comment by kheradmand** [comment]
Thanks Radu. How can I enable the new parser?

**Comment by dwightguth** [comment]
Hi, Radu is talking about using the K 4.0 beta. You can get it by downloading and checking out the latest master on github and passing the "--kore" flag to kompile and krun (although the option will become the default in the next couple days). This should be sufficient for you to use the K 4.0 beta, although there are a number of differences in the K language that mean that you will have to modify your definition if you wish to go this route. I suggest you take a look at https://github.com/kframework/k/blob/master/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k to see a general picture of how the definition needs to look in order for it to work with K 4.0. If you run into bugs or unexpected behaviors please let us know though because it is a work in progress and may not be 100% reliable.

**Comment by kheradmand** [comment]
I get this error with the latests build:

```
[Error] Compiler: Module Map must be visible at the configuration declaration,
in module RVM-SYNTAX2
```

I also tried to kompile tutorial/1_k/1_lambda/lesson_1/lambda.k and got the following error 

```
[Error] Compiler: Could not find sorts: [Id]
    Source(/home/ali/FSL/kbuild3/tutorial/1_k/1_lambda/lesson_1/././lambda.k)
    Location(4,18,4,36)
```

**Comment by bmmoore** [comment]
We are updating the tutorials starting with the last lessions (to make sure all features work), in lambda only `lesson_9` that works: https://github.com/kframework/k/blob/master/k-distribution/tutorial/1_k/1_lambda/lesson_9/lambda.k

Those particular errors happen because the latest build stopped automatically importing any modules. You can see how it's done in the updated tutorials. You will need to add `require "domains.k"` to the top of your file and `include` more modules yourself. Three new modules to help with that are
- `DOMAINS-COMMON`, which declares sorts Id, String, Int, and Bool (without adding the concrete syntax of Id, to avoid comflicts with variables)
- `DOMAINS` which includes other stuff you usually want in a semantics module, including Map, and also extends the sorts from `DOMAINS-COMMON` with things like the `_+Int_` operator that you usually don't want in your concrete syntax
- `DOMAINS-SYNTAX` which pretty much exists to define the concrete syntax of Id, and in theory defines any other concrete syntax you want in your syntax module but not in your rules.

**Comment by bmmoore** [comment]
Also, you got the original error because 3.x uses a regular expression syntax based on the SDF tools (while 4 switches to Java regular expressions). If you want to try to keep using the released version the documentation here might help: http://www.meta-environment.org/doc/books//syntax/sdf/sdf.html#section.symbols
We are trying to move away from SDF and I don't know it very well myself, but the SDF version of your regular expression might be something like `Token{~[\{\}]*}` or maybe `Token{(~[\{\}])*}`.

**Comment by laurayuwen** [comment]
@kheradmand I can update every lesson in lambda today. 
@bmmoore As I said yesterday, there is no backstick in lambda, so lambda don't need back and forth changes. Also, I got stuck when I tried to upgrade 5_types, I need unification hook.

**Comment by kheradmand** [comment]
thanks a lot it worked :+1:
