### ISSUE TITLE
optional cell

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1825]
The design document says that an optional cell introduces additional cell label `no[CellName]` that represents absence of the cell:
https://github.com/kframework/k/wiki/KAST-and-KORE#cells-configurations-and-configuration-abstraction

For example, the following cell declaration

```
 <a multiplicity="?"> .K </a>
```

is supposed to be encoded as:

```
syntax ACell ::= "noACell" | "<a>" K "</a>"
```

But the current implementation uses ".ACell" instead of "noACell" as an encoding of the absence. @bmmoore, is that a bug or an intended behavior? Isn't the unit cell supposed to be used for the multiplicity-star cells? Did you generalize multiplicity-optionals as multiplicity-stars?

**Comment by bmmoore** [comment]
It's definitely not intentional that this disagree with the wiki.
We do probably want full K to allow similar syntax or even just a "." for either case, but I see no reason the klabel shouldn't match the wiki. However, some code may current assume that the lack of a multiplicity ? cell uses a label named similar to the lack of any of a multiplicity \* cell.

**Comment by bmmoore** [comment]
I think your pull request fixes the bug you were running into, but we should also discuss and update the design. I think consistency with other collections demands at least that `.CellName` be allowable concrete syntax for an empty bag of multiplicitly \* cells.
