### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#1843]
I have the following syntax 

```
require "domains.k"

module TEST
    imports DOMAINS-SYNTAX

    syntax LTLFormula ::=
          "empty"
         | "o" LTLFormula   [klabel('LTLO)]
    syntax Param ::= Id Id [klabel('Param)]

endmodule
```

When I try `kast -s Param -e "Object o"` I get 

```
[Error] Inner Parser: Parse error: unexpected character 'o'.
```

Why I get this and how can I fix the error?

**Comment by kheradmand** [comment]
fixed by adding 

```
syntax Id ::= "o" [avoid, token]
```

Wondering whether there is neater way

**Comment by kheradmand** [comment]
"size" is also not an Id. Where can I find a list of reserved words?

```
require "domains.k"

module TEST
    imports DOMAINS-SYNTAX
    syntax X ::= Id
endmodule
```

```
 kast -s X -e "size"
[Error] Inner Parser: Parse error: unexpected character 's'.
```

**Comment by bmmoore** [comment]
There is no fixed list, that's happening because of the `autoReject` keyword on the production for `Id` in `domains.k`.

But, that's only supposed to reserve words that are used as terminal in other productions. If it's excluding "size" it might be incorrectly considering productions that are not actually imported into your module.

@radumereuta should know more.

**Comment by radumereuta** [comment]
Usually, you can solve this by creating a special module for the language of your syntax.

```
module TEST-SYNTAX-COMMON
  // syntax which belongs in the semantics, as well as in programs
endmodule
module TEST-SYNTAX
  imports TEST-SYNTAX-COMMON
  // syntax which belongs in the programs, but will break the complex
  // structure of rules. This is where one should declare stuff like ID
endmodule
module TEST
  imports TEST-SYNTAX-COMMON
  // main semantic module, where one can define semantic rules and
  // auxiliary syntactic constructs
endmodule
```

Now, a few reasons why ID has `autoReject`.
We have the common case, and the advanced case. For the common case,
we want users to get to a result very fast, without them requiring to know too much about
how K works. That's why we invented the `autoReject` tag. It simply looks in all the imported productions for terminals that might collide with the current regular expression, and rejects it from the parse. A common case would be keywords in programming languages like C: `return;`. This would otherwise be ambiguous: return from current function or lookup the variable return.

For the advanced case, the user can use modularity for better control of the syntax used in different modules. The goal is to allow the user to create a parser from any module, at any time. We are in the process of doing that, but we're still working on making it available and finding the best API for the user to use. So feedback on usability is most welcome.

**Comment by bmmoore** [comment]
But @radumereuta, the simple example @kheradmand shouldn't have any conflicting terminals in the syntax module, unless maybe there's a bad import in `DOMAINS-SYNTAX` that pulls in a `size` function from some collection instead of just importing the syntax.

**Comment by radumereuta** [comment]
I just tried this: `kast -e "size(.Map)"`. Apparently there is a step which includes the module DOMAINS in the main module, and for good reasons, it is the main module.
If someone needs something more complex, then modularity is available.

**Comment by bmmoore** [comment]
This works:

```
require "domains.k"
module TEST-SYNTAX
  imports DOMAINS-SYNTAX
  syntax X ::= Id
endmodule
module TEST
  imports TEST-SYNTAX
endmodule
```

then

```
$ kast -s X -e "size"
#token("size","Id")
```

**Comment by kheradmand** [comment]
Thanks a lot @radumereuta @bmmoore

**Comment by radumereuta** [comment]
Can we close this?

**Comment by kheradmand** [comment]
I don't know whether you asked me or other K members but my problem is solved :+1:

**Comment by dwightguth** [comment]
This doesn't seem quite right to me. The default module for `kast` should be the syntax module which in this case is TEST. TEST does not import DOMAINS. So it  should not reject the size keyword. There still seems to be a bug here to me.

**Comment by radumereuta** [comment]
The tests suggests that DOMAINS is included in the main file, but not in the syntax module.

**Comment by dwightguth** [comment]
in the example as listed, DOMAINS is not imported at all. So I am not quite sure what you are getting at, but it definitely doesn't sounnd correct to me.

**Comment by bmmoore** [comment]
MAP, which has a production using terminal "size", is added to the imports of the configuration module.
In the absence of an explicit configuration, DEFAULT-CONFIGURATION is added to the imports of the main module, which is TEST.

**Comment by dwightguth** [comment]
Ah, I see, okay. Yeah, this can probably be closed then.
