### ISSUE TITLE
Add versioning to kserver

### ISSUE THREAD

**Issue by pdaian** [kframework/k-legacy#1867]
When kserver is called from kompile or krun, version info should be exchanged as part of the protocol to ensure no inconsistencies between the two.  This is useful for devs with multiple versions of K, users who are upgrading between versions of RV-Match, etc.  The current latest commit hash can be used as in the version message.

**Comment by laurayuwen** [comment]
Added to K Wish List.

**Comment by dwightguth** [comment]
This should be relatively easy to do. We already serialize the commit hash to the jar so it can be accessed by java, we just need to also serialize it somewhere it can be read by the k shell script, and then pass it in as an environment variable.

The one thing I'm not 100% sure on, though, is, what kind of behavior do you have in mind if it's not a match? Just because it's not a match doesn't mean the boot sequence knows how to find a kserver that does match, so unless you have a specific proposal, I don't know how to do much more than "fall back to not running kserver"

**Comment by dwightguth** [comment]
I will get to this when I get back from vacation after Thanksgiving.

**Comment by pdaian** [comment]
Intended behavior should be something like a warning about running multiple incompatbile copies of the same kserver which will slow down the operation, instructions on how to kill the kserver, and proceeding without kserver.
