### ISSUE TITLE
Synchronization and Concurrency in K3.6

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1868]
I have threads with a certain property in my environment, and I need a certain rule to apply to all of them at once. I assumed that rules will apply concurrently whenever they can as long as no shared writing was involved, but my experimentation tells otherwise.

```
rule [1]: <thread>... 
   <k> synchMe(K) => synchMe(doSomething(K)) </k> 
   <flags> .Set => SetItem("Done") </flags>
...</thread>

// doSomething is processed in a separate rule

rule [2]: <flags> SetItem("Done") => .Set </flags>
```

What I want is for rule 1 to apply on all such threads and then for rule 2 to do so, but what is happening is that rule 1 applies and then rule 2 for each such thread. I tried to say "when all such threads are done" using the `#configuration` function as was suggested in #1836, but that hasn't worked for me yet.

My question here is very general: how do you synchronize threads in K? And why don't rules apply concurrently when they can? Hasn't K been boasting about concurrency with shared reads?!

**Comment by bmmoore** [comment]
Applying them concurrently in each thread is a possible order that will probably be found by `--search`, but nothing in your definition prevents the second rule from applying earlier. @cos is working on strategies, which should be able to directly express that you want to use rule 2 only if rule 1 can't apply anywhere. Otherwise, you'll have to make the synchronization more explicit in your definition.

The somewhat nicer concurrency handling in K consists of deciding that if you do decide to apply that rule in each of the threads, that those are actually non-interfering parallel actions (instead of just being allowed to interleave in arbitrary ways).

**Comment by omarzd** [comment]
@bmmoore, I don't understand that last long sentence. Please rephrase it. 

And regarding `--search`, correct me if I'm wrong, but it won't explore different possible order of applying rules unless these rules are declared transitions. 

And thanks for your suggestion. I already made synchronization more explicit like you said.

**Comment by bmmoore** [comment]
I think in the current version `--search` should work without declaring things transition.

The concurrency feature in K is being able to decide that two rules can apply at the same time because any parts of the configuration which both match are used in read-only ways. This is not at all the samething as somehow implicitly banning executions that decide to run the rules separately. K allows more concurrency than other frameworks, but it doesn't force all possible concurrency to execute synchronously.

That would be incorrect anyway - suppose two threads are ready to read from the heap and one was going to modify it. If K's "boasting about concurrency with shared reads" somehow meant that the reads were forced to execution together, than the semantics would miss the possible execution where the write is interleaved between them.

**Comment by cos** [comment]
@omarz1, you can do that using the strategies functionality on master. Declaimer: it's very much experimental, and you'll lose performance for now. If you want to try that, let me know and I'll help with making it work.

**Comment by omarzd** [comment]
I understand now. Thank you.

**Comment by omarzd** [comment]
@cos, this is the third time you tell me to use master. So I'll try to clone and compile it today.

**Comment by grosu** [comment]
Yes, @omarz1 , we are on a fast track to release K 4.0, and we do not have any resources left to improve or maintain other versions.

**Comment by omarzd** [comment]
@grosu, I just needed to produce some results for my research and I couldn't risk updating at that moment. Now I can and I will. You'll know when you see me reporting bugs :smile:.
