### ISSUE TITLE
Parsing errors off by +1 line

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#1883]
Example:

```
odule Test
endmodule
```

@cos thinks that this comes because @dwightguth added `requires "domains.k"` by prepending it to the text.
I think it should be added programmatically. The original text should not be changed before sending it to the parser.

**Comment by dwightguth** [comment]
You are correct, that seems to be the cause of this, because it does not affect anything other than the very entry-level file. Unfortunately, that means it doesn't really affect me in any way. I will only be able to get to this after I no longer have higher priority tasks to accomplish, which may be some time (my guess is on the order of weeks). You may want to fix this yourself.

**Comment by radumereuta** [comment]
Can you at least pinpoint the place where you are doing this?

**Comment by dwightguth** [comment]
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kompile/Kompile.java#L252

**Comment by daejunpark** [comment]
@radumereuta was it fixed via #2019?

**Comment by radumereuta** [comment]
It should be, yes.
