### ISSUE TITLE
Strange klabel error with java engine

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#189]
(Most likely this is for Andrei S, Traian and Yilong)

In the lambda.k type inferencer, you have the klabel(schema) associated to the type schema construct, although you never use it.  When I remove that useless attribute, krun throws a huge exception (I had to Ctrl-C it, because it would not terminate displaying it!).

**Comment by yilongli** [comment]
I can take a look. Running which program did you get the exception?

**Comment by grosu** [comment]
definition k/samples/java_rewrite_engine/tutorial/1_k/5_types/lambda.k
program exponential-type.lambda in the same folder.

**Comment by andreistefanescu** [comment]
The issue here is with the fact that there is another production forall_._
in the prelude files, and there are conflicts between the two (for example
one has the function attribute, and the other doesn't).

Andrei

**Comment by grosu** [comment]
And how should we solve it?  Note that this used to work a few days ago.  The current solution, to add a klabel, is quite adhoc.  A typical example of precisely what we should avoid.

**Comment by andreistefanescu** [comment]
Hmm, I don't know exactly what is going on in this particular case. In the
git repository, the klabel attribute was always there. If you changed in
your local copy and it worked, than you just got lucky.

I would argue that in general we should not allow a klabel to be both a
function and a constructor. So using a klabel attribute does not seem adhoc
to me. We could avoid the whole issue by just renaming one of the
productions (and if I remember correctly, we already had some other
problems because both productions have the same name).

Andrei

**Comment by grosu** [comment]
Andrei,

Both lesson_5.5 and lesson_9.5 worked under 5_types in the tutorial when I taught them in class, and none of them had the klabel.  Also, everything works just fine with the old rewrite engine, which I assume also sees the forall in the prelude.  BTW, I was actually not able to find any forall_._ in the prelude, where is it?  And is it indeed a function?  Of course, I agree that a klabel cannot be both a constructor and a function, but throwing a non-terminating exception when this happens is certainly not the way to do.

In general, please do not defend bad design and contrived ways of doing things.  They do not help us get a better system.  If any of us gets tyricked with the way things are, particuarly myself who uses K in lots of different instances and contexts, then it means that things are bad and need to be changed.  It is simply bad to just add a klabel to a production and then suddenly everything works.  I still don't even understand why this happens.  Can you explain how the klabel makes any change which makes conceptual sense?

First, the most obvious thing here is that some error should be given when one overrides an operation which has already been defined.  This is also related the other discussion we are having in parallel with this one, with the + and - prefixes to operation attributes.

Second, we should move on and include the entire signature of the operations in labels.  We keep discussing this for ages, but no move has been done in this direction.

The two things above will probably go a long way towards avoiding this kind of problems.

Grigore

**Comment by andreistefanescu** [comment]
I investigated further, and this specific problem is generated by the
conflict with forall_._ in include/builtins/symbolic-k.k, line 19. It is
not because of the function attribute, but because of the binder attribute.
Still, the same issue. It also explains the sudden change in behavior,
since there has been recent work on the binders.

I am not defending bad design. I completely agree that we should give an
error/warning message. It is just not implemented yet.

To explain why this works the way it does, consider the fact that certain
attributes are not really associated to productions, they are in fact
associated with klabels. So if you have two identical productions with
different klabels (and this can only happen if at least one of them uses
the klabel attribute), if you manage to parse, then you end up in kore with
two completely different klabels, which are going to behave in completely
different ways. The same could happen with strictness. If you have a strict
attribute on one production, but not on the other, they are both going to
be strict. But if you put a klabel attribute on the one which is not
strict, then you get a different behavior. I think we should discuss about
it, and agree on what should happen here.

Andrei
