### ISSUE TITLE
KTest options to skip kompile, PDF phases

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#19]
For working on K, it would help to have command line options we could use to skip PDF generation and/or kompile without editing the config.xml

**Comment by radumereuta** [comment]
Since I'm working on kompile, I would like to call only the kompile step. Don't bother about PDFs or programs.

I think the best thing would be to have 3 options: ktest -kompile | pdf | programs

**Comment by grosu** [comment]
Andrei's got lots of feedback from us on ktest now, so let's lel him come up with some consistent options to make everything we want ktest to do smooth.  And, as usual, things should be designed so that the common case (when one wants to test everything, both kompiling definitions and running programs) is fast.  Andrei, if you need to further discuss things with us, please do it through the k-list.

**Comment by andreiarusoaie** [comment]
I think I found a solution, but I'm not sure everybody agrees with it. What I did was to add --skip option:

-skip <arg>               The list of steps separated by whitespace to be
                           skipped (kompile/pdf/programs)

which gets a list of steps separated by whitespaces saying which step should be omitted. For instance:

ktest --config tests/config.xml --skip "kompile pdf"

will only check the programs. 

Probably Brandon can use ktest --config tests/config.xml --skip "pdf" to ignore pdf creation for all the definitions. 

I'm closing this, but feel free to reopen it if needed.
