### ISSUE TITLE
KTest default results directory

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#20]
When ktest is recursively searching for programs under a directory, and a results directory is also given, it wasn't clear where the IO for a program should be found.
Some definitions have subdirectories matching the program directories, others have just one results folder with all the expected IO at the root. So, we decided in the K meeting that that's a reasonable default - first look in the corresponding subdirectory, then try the root.

**Comment by grosu** [comment]
I just ran into this issue again.  I want to move all the results for the languages in the tutorial/2_languages together with the actual examples, in the same folders.  For example, I want this:

fslwork$ pwd
/home/grosu/k/dist/tutorial/2_languages/1_simple/1_untyped/programs
fslwork$ ls
diverse  exceptions  threads
fslwork$ ls *
diverse:
collatz.simple      factorial.simple.in      matrix.simple.out
collatz.simple.in   factorial.simple.out     sortings.simple
collatz.simple.out  higher-order.simple      sortings.simple.in
dekker.simple       higher-order.simple.out  sortings.simple.out
div-nondet.simple   matrix.simple
factorial.simple    matrix.simple.in

exceptions:
exceptions_01.simple      exceptions_06.simple.out   exceptions_11.simple.out
exceptions_01.simple.out  exceptions_07.simple       exceptions_12.simple
exceptions_02.simple      exceptions_07.simple.out   exceptions_12.simple.out
exceptions_02.simple.out  exceptions_08.simple       exceptions_13.simple
exceptions_03.simple      exceptions_08.simple.out   exceptions_13.simple.out
exceptions_03.simple.out  exceptions_09.simple       exceptions_14.simple
exceptions_04.simple      exceptions_09.simple.out   exceptions_14.simple.out
exceptions_04.simple.out  exceptions_09.simple.out~  exceptions_15.simple
exceptions_05.simple      exceptions_10.simple       exceptions_15.simple.out
exceptions_05.simple.out  exceptions_10.simple.out   junit-reports
exceptions_06.simple      exceptions_11.simple

threads:
threads_01.simple  threads_06.simple.in   threads_10.simple
threads_02.simple  threads_07.simple      threads_10.simple.out
threads_03.simple  threads_07.simple.in   threads_11.simple
threads_04.simple  threads_07.simple.out  threads_11.simple.out
threads_05.simple  threads_08.simple      threads_12.simple
threads_06.simple  threads_09.simple
fslwork$ 

Now that ktest has become a tool that any user can use, it makes sense to do this.  Now, what I'd like to do to test all of them is:

fslwork$ ktest -d ../simple-untyped.k --skip "kompile pdf" --programs . --extensions simple

(well, once the -d bug is fixed in ktest, which I reported before, the above would be even simpler)

Unfortunately, the above gets stuck, because it does now know where to look for the results.  I would say that this is becomming probably one of the most common cases, so we must make it work soon.  I actually need it for my class, because I want to provide students with lots of examples for their HWs, and each HW will have its own directory, with its own examples.

**Comment by grosu** [comment]
The principles here are simple and separate:
1) by default, --results is the same as --programs
2) when searching for the IO of a program P, search first under the results folder at the same relative path that P had under --programs, and if that does not exist then search for it at the top of the --results folder.

**Comment by andreiarusoaie** [comment]
1) is fixed
2) It is not clear at all for me what you want, in the sense that I cannot understand what do you exactly mean by: 
"search first under the results folder at the same relative path that P had under --programs". For instance, let us consider this example:

< test
      definition="dist/tutorial/2_languages/1_simple/1_untyped/simple-untyped.k"
      programs="dist/tutorial/2_languages/1_simple/1_untyped/programs"
      extension="simple"
      exclude="diverse/dekker.simple"
      results="tests/tutorial/2_languages/1_simple/1_untyped/"
      />

You want me to find some kind of matching between programs and results? I don't really have in mind a nice and clean solution for this. Right now, ktest searches for the most in depth results for a given test: if results=tests/tests/tutorial/2_languages/1_simple/1_untyped/ and it also contains as subdir (tests/tests/tutorial/2_languages/1_simple/1_untyped/)diverse/ then ktest finds factorial.simple.out under diverse/ dir and ignores any other factorial.simple.out from  tests/tutorial/2_languages/1_simple/1_untyped/.

**Comment by grosu** [comment]
So if I understand it correctly, you work with flat sets of programs and results, rather then with nested sets, one per subfolder.  In other words, the --programs folder tells you where to collect your set of programs from, and --results tells you where to collect your set of results from, right?  Then, once you have the two sets, of programs and res. of results, you just run each program and test it against its corresponding result.  If that is what you do, then you should keep it that way, but please put a simple explanation somewhere (for now, putting it in the --help text can be good enough).

What I recommended was based on a different assumption.  That you works with nested sets od programs, one for each subfolder under --programs.  Then for each such subset, you need a subset of results.  My suggestion was related to how to compute the set of results: first try to find it under the same relative path under --results as its programs subfolder was under the --programs folder; if that subfolder under --results does not exist, then default to the results found in the folder --results itself (and not in its subfolders).

However, no need to implement what I thought.  Your current approach is just as good, provided that it is properly explained.

Thanks.
