### ISSUE TITLE
silly and annoying parsing error

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#200]
Took me awhile to minimize my example to pinpoint this error:

```
fslwork$ cat try.k
module TRY
  syntax Exp  ::= Id
                | Id "{" Exp "}"
  rule X:Id{_} => X
endmodule
fslwork$ kompile try.k
[Error] Critical: Parse error: Syntax error near unexpected character '{'
    File: /home/grosu/try/try.k
    Location: (4,12,4,12)

```

If I replace X:Id with X in the rule, or if I replace the curly brackets with anything else, including normal parentheses, everything works.

**Comment by radumereuta** [comment]
At one point we had List{K}, and we thought of including all sort of List{Sort}.
I added a follow restriction after variables to not allow { in order to avoid certain ambiguities.

Since we don't plan to use such sort names, I removed that follow restriction, along with List{K}, which stood in deprecation for long enough for people to remove it completely.
