### ISSUE TITLE
do priorities work?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2000]
I spent 15 minutes trying to make priorities work for lambda, lesson 1:

```
syntax priority lambda_._ > __
```

etc.  Tried lots of variants and nothing worked as I wanted with `krun`.  The default priority is the right one in krun, that is, `lambda x . x y` is displayed as `lambda x . (x y)` in the k cell by krun, but I cannot make it do the other parsing, `(lambda x . x) y`.  I tried putting the labels in backticks and that didn't work either.  I tried reversing > into <, nothing.  It appears that I can even use a wrong label name, say _._, and get no error.  On the other hand, kast reports an ambiguous parsing warning on the same input.  How comes krun silently ignores the parsing warnings that kast reports?  That should not happen.  Anwyay, I threw the towel, I have no idea how to make this work.  What's going on here?  We need at least to report errors when people misspell the KLabels, and to have krun report the warnings/errors reported by kast.

@radumereuta , please fix/elucidate.  Also, once done, please add an explanation in the manual wiki.  If this is indeed a bug and it is hard to fix, it is OK to postpone until after Jan 18, provided it does not interfere with the other tutorial examples.

**Comment by radumereuta** [comment]
I have a few suspects:
1. In K3.6 we generated klabels with a quote in front. @cos didn't like that, so he stripped them programatically in some places. Maybe that code wasn't so clean. I will have to do some serious digging to confirm and fix this.
2. In the new implementation krun calls the parser via kast (external command line call). It may be that krun ignore the warnings reported by kast.

I would like to propose something that I wanted to enforce for a while now because it's a reoccurring issue: make ambiguities errors instead of warnings. This way compilation stops, and we force the users to fix their definitions. We had repeated problems with tests failing after a patch which switched the order of ambiguities. I don't think this fixes completely the issue above, but it would make it surface a lot sooner, which could help me solve it faster.

**Comment by grosu** [comment]
1) It was all the time just _plain wrong_ to rely on the particular name of a KLabel, whether it starts with a quote or not, etc.  If you need to keep track of information about it, then that information should be stored as attributes of the KLabel object.  Relying on the name in order to figure out information about the KLabels is fragile.  If you can fix this quickly then fine, otherwise please something else to work on, which is a deal breaker for the transition to K 4.0 (the tutorial must work, that is a deal breaker).

2) I would still keep then as warnings, but ones that are displayed by `krun`.  Maude does the same thing.  Moreover, PLD-REDEX and other evaluation context based approaches use parsing ambiguities as means to deal with non-determinism.  Considering the tough deadline, it may be better to not even open this can of works right now.  All we need is to make sure the tutorial works.  You can file it as an issue to take care of afterwards.

3) Note that we should also report an error whenever one explicitly refers to a KLabel that has never been declared.
