### ISSUE TITLE
.Ids seems to be needed in rules now

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2023]
In https://github.com/kframework/k/tree/master/k-distribution/tutorial/1_k/2_imp/lesson_4 we say:

```
The use of the .Ids in the second rule is not necessary. We could have written int; S instead of int .Ids; S and the K tool would parse it and kompile the definition correctly, because it uses the same parser used for parsing programs also to parse the semantics.
```

It turns out, though, that now we do need to add the `.Ids` in the second rule for variable declarations.  The parser does not complain if you don't, but the programs fail with `int .Ids` on top of the `k` cell when you run them.  We may continue to argue whether we want lists to be automatically associative or not and whether we want the `.` units to be explicit in the rules, but whatever we decide, we cannot have the parser not complain and let the program kompile, only to fail to match at runtime.

**Comment by radumereuta** [comment]
But this is a really really old text. git blame tells me you wrote this in 2012.
I think this is what used to happen in K2, but we found that we don't want to allow terms which match on 'nothing' in rules because we may be able to write unreadable stuff like `rule X =>`.

In this case, to parse `int ; S`, we would have to add a term `Ids ::= ""`, but something like this will produce unmanageable ambiguities, and malformed rules.

I think the text should be updated.

**Comment by grosu** [comment]
Maybe I should change the readme text, indeed, but I will only do it after the parser rejects `int ; S`.  It currently does not, as I said above.

**Comment by radumereuta** [comment]
That's interesting. I tried to parse this: `rule int ;   [structural]`, and works!!!!
Something is very, very, VERY wrong in kompile.
How did this pass through our tests?

**Comment by grosu** [comment]
Isn't that the same I said?  :)

**Comment by radumereuta** [comment]
This has nothing to do with parsing. I'm looking into it with @dwightguth.

**Comment by radumereuta** [comment]
Ah, and please don't merge anything until we have this fixed!
