### ISSUE TITLE
test or steps to replicate for the issue behind #2027

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#2035]
@radumereuta, @dwightguth, please document (test or at least steps to replicate) as soon as possible the problem that required you to revert my #1962 PR via #2027. It has already been a day since and and I am blocked because of it.

If this is not fixed soon, I will not be able to complete the kdoc functionality by the 4.0 deadline.

**Comment by grosu** [comment]
@cos, it may have been my fault, with #2023, because the messages started immediately once @radumereuta realized there was a problem there.  But not sure.  If it is only that problem that triggered the entire thing, then I would not be that concerned.  I mean, we can merge, add a comment in the definition and modify the readme (myself), and move on with our deadline and fix the problem afterwards.

Another thing, @cos: if it is to make a compromise to drop something in order to catch the deadline, I would say that we can drop kdoc and do it (first thing) after the deadline.  It is more important to have superheat work in order to demonstrate the search capabilities of the framework than kdoc.  Besides, kdoc will require a lot of tuning, I am pretty sure, until we are 100% happy with it.

**Comment by dwightguth** [comment]
@cos the extent of my reproduction steps was that I wrote a rule that did not parse and kompile terminated successfully anyway. If you can't reproduce following those steps I suggest you talk to @radumereuta because he seemed to think he had some easily reproducible test case.

**Comment by cos** [comment]
@grosu, I guess that was the problem that triggered the entire thing. I'm not sure as I have no more details -- the reason I added this issue. The reverting PR has been merged so, if my PR was the problem, it should be fixed now. But I'm blocked regarding kdoc because that branch is directly dependent on the reverted refactorings and adds more, and I don't want to go into juggling multiple branches with various levels of refactorings and fixes over the same code. I will wait for more details from @radumereuta or @dwightguth before getting back to it.

Regarding superheat, the current strategy implementation, given the right strategy, should already be capable of that. We just need to play with it, smooth any rough edges, and hook it to the command line arguments.

**Comment by dwightguth** [comment]
I can tell you right now it was not just that definition because I actually
independently was already working on the bug after it arose in the C
semantics when Radu contacted me. We really can't merge this until it's
fixed because it makes it next to impossible to do any development in the K
language.

**Comment by cos** [comment]
thanks @dwightguth, I will try that.

**Comment by dwightguth** [comment]
I suggest you also try it with and without a version of that rule in the
cache, if that's not enough to reproduce it.

**Comment by cos** [comment]
Simply having a non-config error in the rule failed to trigger the required exception. I missed that because error tracking is handled orthogonally to the main program logic (i.e., methods return even when there are errors and it is the responsibility of the method caller to also check the error set). I will try to make that harder to break by making it more functional style -- methods to return the error set instead of accessing it via a mutable field.

In any case, in the meantime, I reverted the revert and fixed the problem: #2036. Please try it out but don't merge before I add a negative test.

**Comment by cos** [comment]
addressed by #2036
