### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#211]
What is the level of IDE support and what is the roadmap to improve this?

**Comment by radumereuta** [comment]
Because we support concrete syntax in the rules, parsing K definitions is not trivial. That's why IDE support is harder than any other DSL, and since we are still experimenting with new and better ways to parse our definitions, creating an IDE is hasn't been our priority.That doesn't mean that it won't be in the future. At the moment we provide some configuration files for a few popular editors in order to get syntax highlighting.
You can check them in the directory /editor-support.

**Comment by sirinath** [comment]
Great. Looking forward to this.

**Comment by sirinath** [comment]
If you have a K definition of K' and a framework to generate tools for a K definition then the tools can evolve with K with having to extensive rework for K'. Full suit of can be created including IDE support, parsers, etc.

Just a idea

**Comment by sirinath** [comment]
Just another suggestion. 

Perhaps you can have a formal language to generate different types of tooling also to fill in the gap if this cannot be fully generated from the definition of new K.

**Comment by sirinath** [comment]
http://peaker.github.io/lamdu/

Interesting concept

**Comment by dwightguth** [comment]
Closing. Please reopen if you still have questions.
