### ISSUE TITLE
Whole numbers always parsed as Ints

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2171]
```
syntax Pgm ::= foo(Float)
rule foo(0) => .
```

`kompile` will give a syntax error here because it's expecting a float in place of `0`. 
`0.0` will work. But why can't it be inferred like with variables?

**Comment by radumereuta** [comment]
If you look over the syntax of floats: 
https://github.com/kframework/k/blob/master/k-distribution/include/builtin/domains.k#L317
`0` is actually never parsed as a float. You have to say either `.0` or `0.`.
This is intended because, in some languages, where you have a common super sort of both Int and Float (like Exp), you will always get an ambiguity at parsing time, requiring an extra step of disambiguation.
Note that for your language, there is nothing stopping you from having such a case. We just chose to do it this way for simplicity.
