### ISSUE TITLE
error with klabel \\\_.\_ in samples/agent

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#2194]
KLabel \_._ causes krun to crush. In the backend, the label becomes ._, and that seems to be the problem.

**Comment by traiansf** [comment]
@radumereuta I've created a minimal example to ease your task.
Interestingly enough, compilation works just fine, the error arises only when attempting to run a program.

[minimal-example.zip](https://github.com/kframework/k/files/407619/minimal-example.zip)

**Comment by radumereuta** [comment]
I think I found the problem. The output of kast is incorrect. The klabel of the production `Exp ::= "\\" Id "." Exp` should be ``\\_._`` because backslash is the escape character, and when pretty printed like that, should be doubled.

The problem is that I don't know how to proceed with the fix because the escape function is in `kernel`  `StringUtil.escapeKoreKLabel`, and the unperser is written in scala, in the `kore` module, which doesn't import the first one.

@cos, can I get some assistance with, what seems to be, a refactoring issue?

**Comment by cos** [comment]
Moved the relevant functions to the kore module:
https://github.com/kframework/k/tree/hotfix/2194

Could you do the rewiring to use them?

**Comment by radumereuta** [comment]
@traiansf please review.
