### ISSUE TITLE
Parser accepts `/* ... */` comments implicitly

### ISSUE THREAD

**Issue by nishantjr** [kframework/k-legacy#2337]
This implicit behavior doesn't allow writing syntax, e.g. for python where this style of comments should not parse.

**Comment by radumereuta** [comment]
Currently, the K parser doesn't allow you to specify indentation sensitive languages.
Layout is handled automatically and uniformly. In order to parse Python, the parser needs a bit more work.

Regarding comments, it is actually relatively easy to specify different styles, but we could never agree on a way to specify them, so I just chose the most common example (C style of comments) and hard coded them.

**Comment by nishantjr** [comment]
Ah, didn't realise that. Thanks!
