### ISSUE TITLE
Investigate using a dependency injection framework

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#245]
Static state is bad. e.g. GlobalSettings, etc. This is what beans are for. We need to think about using something like Guice or Spring in order to keep track of our configuration settings. I lean toward Guice because I found this: https://github.com/israfil/jcommander-inject/tree/master/guice

**Comment by radumereuta** [comment]
Having a discussion on this would be a good idea. We should have present everybody who works on the K-tool code. At the moment there are several dependencies to static fields that are limiting factors.

I want to have an open discussion, because removing static fields is really important for modularity: parsing and disambiguation at a module level. I don't think it's possible with what we have right now. I would like to have a meeting where we go through few of the scenarios that should happen and some ground rules that we should respect from now on.

I know that I would definitely benefit from such a meeting because I'm at fault for introducing some of those dependencies a long time ago :)

**Comment by dwightguth** [comment]
I'm glad you're on board. I will share what I know about dependency
management when we discuss this. I think you'll be very impressed what
modern open source software can provide for us.

**Comment by denis-bogdanas** [comment]
Dwight, I'm glad you made this proposal. I proposed using DI and a command line parsing API myself a couple of months ago. I guess after you've left. I have a lot of experience with Spring, never used Guice. And the integration that you suggested looks like an important plus for Guice. For spring I have only found this:

https://github.com/sazzer/spring-cli

**Comment by dwightguth** [comment]
Closing. Used Guice.
