### ISSUE TITLE
hundreds of parsing ambiguities in builtins

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#259]
The syntax module defined below gives hundreds of parsing ambiguities, all of them in builtin files. Please replace this output with something relevant.

module SDF-SYNTAX

syntax Module ::= "module" Id
                  "imports" ImportsList
                  "exports" ExportAttributeList IdList

syntax ImportsList ::= List{FilePath, " "}
syntax FilePath::= List{FileName, "/"}
syntax FileName::= Token{[a-zA-Z][a-zA-Z0-9_]*}

syntax ExportAttributeList ::= List{ExportAttribute, " "}
syntax ExportAttribute ::= "context-free" | "start-symbols" | "sorts"

syntax IdList ::= List{Id, " "}

endmodule

**Comment by denis-bogdanas** [comment]
By the way. I'm trying to parse the attached file. How should I handle lists of items separated by spaces / new lines?

module java
imports
  languages/java-15/Main

exports
  context-free start-symbols
    CompilationUnit

**Comment by radumereuta** [comment]
Denis, the reason you get so many ambiguities is because you declared FileName as being a Token which resembles K meta-variables. Since at the moment SDF doesn't allow me for proper modularity, there is no easy way to stop the ambiguities to happen in the /include directory.

As a workaround, I suggest you put the attribute [notInRules] on FileName. This will tell the parser to not include that production in the Rule parser. If you have problems with the Ground parser too, then you can also use the attribute [notInGround].

You can reference the tokens in a rule with the following notation: #token("FileName", "name of file")(.KList)

**Comment by grosu** [comment]
Radu, please add this explanation also in the "manual", you know where.

Grigore

**Comment by dwightguth** [comment]
We should consider doing two things:
1. erroring out of compilation if there are parsing ambiguities in the
   includes directory.
2. attempting to display a better error message in this case informing the
   user what the problematic production is and why there is a problem

**Comment by dwightguth** [comment]
Closing since this is resolved by the modular new parser.
