### ISSUE TITLE
ktest: timeout

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#26]
For programs which may not terminate, or may take a lot of time, a -timeout option might be useful.

**Comment by andreiarusoaie** [comment]
I'm not sure I can do this easily. Right now I use a ThreadPoolExecutor object which can await for termination a given amount of time. Since I use only one object, I can set the time for the whole configuration which is tested. I will postpone this one until I'll have more time to work with it.

**Comment by grosu** [comment]
Here is some useful info which may help you with this task:

http://stackoverflow.com/questions/671049/how-do-you-kill-a-thread-in-java

**Comment by andreiarusoaie** [comment]
Again, I know that @osa1 worked a bit on adding timeouts to ktest. Omer can you tell us if we can assign timeouts to specific tests?

**Comment by osa1** [comment]
So we also want different timeouts for different test cases? Currently ktest has only one notion of timeout and that's timeout for every process spawned by ktest.

This can be easily implemented, though. I'll add this feature and update this issue today.

**Comment by andreiarusoaie** [comment]
I believe so. It makes sense to have a specific timeout for each <test> at least for those tests which take longer than usual (we need some default). 

However, I think Grigore wants a way to put a timeout on krun calls. Probably, he wants to put them on programs which can run forever; I'm wondering if we need new tags for such special programs, where we also specify when the execution is timeout: success or fail.

**Comment by denis-bogdanas** [comment]
I have timeout implemented for my custom test runner. the solution was to use two thread pool executors. A task in the first executor spawns a task in the second one an then waits for that second task to complete for a specific timeout. If timeout is elapsed the second task is interrupted. Tasks in the second executor actually invoke krun process. This architecture is required because in Java 7 you cannot join a process with a timeout. It will be possible in Java 8, though. I guess Omer intends to do something similar.

**Comment by grosu** [comment]
Thanks for sharing this, Denis.  Yes, it looks indeed like this could also be done generically, in ktest.  Omer said that he also has that functionality, so it would be interesting to compare your approaches.

**Comment by dwightguth** [comment]
Pretty sure this got implemented. Closing
