### ISSUE TITLE
Matching in the middle of a syntactic list

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#266]
Given the following syntactic list:

syntax ObjLayers ::= List{ObjLayer, ","}

And the following term inside a rule:

(_:ObjLayers, X:ObjLayer, _:ObjLayers)

It gives kompile error at the first space.

Looks like matching an element in the middle of a syntactic list is not supported. Tutorial examples all use matching at the beginning of the list. Shouldn't we be able to match anywhere, just like for the sort List?

This feature is quite important for java semantics. Not critical, but would allow implementing more type safety inside complex terms.

**Comment by traiansf** [comment]
Currently this feature is not supported.

We used to support associative syntactic lists in one of the first
iterations of K, but there were issues with it and at that point cons-lists
seemed easier to specify and use.

Moreover, the java rewrite engine currently does not support matching in
the middle of a list even for non-syntactic lists.

The discussion of bringing back associative lists was reopened several
times, but no action has been taken into this direction since we switched
to Java for compilation.

numai bine,
Traian

2014-03-04 13:20 GMT+02:00 Denis Bogdanas notifications@github.com:

**Comment by grosu** [comment]
People working on program transformation and compilation using K also need associative lists.  For example, they want to match a statement inside a block that assigns a certain variable, etc.

This is related to the pm (pattern match) function that backends should provide.  It is a good example why we actually want to isolate that pm function, so that we can separate concerns and address them eventually.  It would be nice to merge the various lists that we have in K, so that we have only one implementation for them (user-defined lists, List, and KList).  The clean way to do it, probably, is to have two different builtins:

List{Sort}{separator}{unit}  --- for cons-lists
AssocList{Sort}{separator}{unit}  --- for associative lists

Or ConsList and List, if we want to encourage people to use the associative lists.

Grigore

**Comment by cos** [comment]
Is the associativity a property of the data structure, or of the matching? 

Having two separate builtins, like List and AssocList, implies that it is a property of the data structure. I don't like this. It means that if somebody decided to use a cons-list at some point when defining the semantics, I'm stuck with not being able to do associative matching without changing his code. 

I think on the K side we should have only have one List builtin which always allows associative matching. If a particular backend doesn't support it, it can raise a warning.

**Comment by grosu** [comment]
Well, you can say the same about sets.  So if you want to do AC matching on a list, you suddenly transform it into a set?  Associative lists, like sets, may have a different API than the cons-lists.

The above being said, I agree that it would be ideal to only have one list datastructure, which should be associative, provided that we do not have to pay any performance price for it.  That is, somebody who only wants to match hd/tl patterns on a list should not be punished with a slower pattern matching.  I think this is doable, though.

Grigore

**Comment by traiansf** [comment]
Maude lists are optimized for access at both ends, so viewing them as cons
lists would definitely be ok performance-wise.

For Java we could implement them as regular lists and have a big penalty
for associative matching.

2014-03-05 18:01 GMT+02:00 Grigore Rosu notifications@github.com:

**Comment by grosu** [comment]
I am OK with that.  We may also want to take a look at ASF and Elan, as they also have associative lists.  I think ASF managed to beat Maude by an order of magnitude in performance when we did our performance tests on associative list rewriting.

Grigore

**Comment by traiansf** [comment]
not really: http://dx.doi.org/10.1016/j.entcs.2007.06.018

apparently in what regards associative lists, ASF managed to beat Maude
only for random access, and there by a small margin.

Traian

2014-03-05 22:19 GMT+02:00 Grigore Rosu notifications@github.com:

**Comment by grosu** [comment]
Cool!  I completely forgot that we actually wrote a paper about this.  Papers seem to be useful, after all :)

So now, Yilong and Owolabi, you've got some numbers to beat.  See the paper.

Grigore
