### ISSUE TITLE
Error: Unable to access jarfile /home/ady/bin/k/bin/../lib/java/k3.jar

### ISSUE THREAD

**Issue by charmpitz** [kframework/k-legacy#276]
This happened after a fresh install of the K-framework. I've attached the following screenshot:

![screenshot1](https://f.cloud.github.com/assets/1377225/2378863/0ce18c86-a894-11e3-820a-ca26f27347a5.png)

**Comment by dwightguth** [comment]
Did you download from source control or from the distribution at
k-framework.org? If the former, this is expected because you need to run
"ant" first.

This happened after a fresh install of the K-framework. I've attached the
following screenshot:

[image: screenshot1]https://f.cloud.github.com/assets/1377225/2378863/0ce18c86-a894-11e3-820a-ca26f27347a5.png

## 

Reply to this email directly or view it on
GitHubhttps://github.com/kframework/k/issues/276
.

**Comment by charmpitz** [comment]
I did " git clone https://github.com/kframework/k.git "

**Comment by charmpitz** [comment]
The solution was to add the k3.jar file from k-framework.org

**Comment by charmpitz** [comment]
But after that i get to issue #277 and i had to combine the github version with the one provided on the k-framework.org

**Comment by traiansf** [comment]
If you use git clone you should build it.

For that you need to run ant in the k top folder

this would create a .jar file in for this particular version from the
sources.

What happened was that probably the .jar file from the previous version (on
the k-framework.org site) was not compatible with the newest source
distribution.

2014-03-10 23:28 GMT+02:00 charmpitz notifications@github.com:

**Comment by grosu** [comment]
Traian, Dwight, can you guys please check whether this is (still) well explained in the README and INSTALL files?  charmpitz, did you find the info in these files insufficient?

Thanks,
Grigore

**Comment by charmpitz** [comment]
It is all clear now but i think there should be something specified about "ant" command for installing. Thanks to everybody for helping me and sorry for my delayed answer.
