### ISSUE TITLE
KLabel use in rules for function does not work well

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#313]
Consider this:

```
module TRY
  syntax KLabel ::= "#foo"
  syntax K ::= foo(K)  [function, klabel(#foo)]
  rule #foo(1) => 0
endmodule
```

If I krun the program `foo(1)` reduces as expected to 0.  However, if I change the program into `foo(foo(1))` it stays unreduced.  On the other hand, if I change the rule to `rule foo(1) => 0` then `foo(foo(1))` reduces to `foo(0)` as expected.

**Comment by grosu** [comment]
And if the above was not confusing enough, it actually seems to work if you add the attribute anywhere to the original rule above.  But of course, that anywhere attribute should be redundant here, because we already said that foo is a function.

**Comment by radumereuta** [comment]
I think the filter that applies 'anywhere' to rules matches on TermCons instead of KApp.
This would explain the behavior.
I don't know who is responsible for this transformation, but you might want to check this first.

**Comment by grosu** [comment]
btw, the same happens with the --backend=java

**Comment by traiansf** [comment]
my guess is that, due to the renaming, the function attribute does not get
propagated to the rule.  And since the java backend shares this
transformation (adding function to rules topped in a functional symbol),
there should be no surprise you notice the same behavior there.

2014-03-27 20:36 GMT+02:00 Grigore Rosu notifications@github.com:
