### ISSUE TITLE
How to specify a syntax production label

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#327]
I have the following rule in my label-based semantics:

syntax KLabel ::= "'ListWrap"
rule  'ListWrap(S1:K,, Stmts:KList) => S1 ~> 'ListWrap(Stmts)

I want to replace the rule with:
[ S1:K,, Stmts:KList ] => S1 ~> [Stmts]

How should I define the syntax for [...] ?

Attempts like the following don't work:

syntax KListWrap ::= "[" KList "]" [klabel('ListWrap)]

Please help. This is pretty urgent. I've searched both the manual and the tutorial.

**Comment by grosu** [comment]
Did you try just 

```
syntax KListWrap ::= "[" KList "]"
```

?

**Comment by denis-bogdanas** [comment]
I need the label to be 'ListWrap, so that I won't have to change the parser.

**Comment by grosu** [comment]
Then try something like this:

```
  syntax KListWrap ::= "[" SomeSyntacticSortDifferentFromKList "]"
  rule 'ListWrap(Kl:KList) => [Kl]  [anywhere]
```

Traian, can you help?  I think the problem is that you are defining something which takes a KList and is not a KLabel, so some sort of injection is going on under the hood.  You can also take a look at the Maude generated code to see what's going on.  Suppose that `stuff(Kl)` is generated under the hood from your `[Kl]`.  Then you can try to modify the rules above into:

```
  syntax KListWrap ::= "[" KList "]"
  rule 'ListWrap(Kl:KList) => stuff(Kl)  [anywhere]
```

Your definitional style in the semantics of Java is in my view kind of unfortunate.  You want almost a KORE definition, but you also want to have concrete syntax over the KORE syntactic categories.  But the problem is that KORE is meant to be a very simple IL, in particular one where you cannot define anything else except KLabels that take KLists.  It is the job of the front end to automatically desugar those and encode them into a simpler KORE.

The right way to write your definition is to define a concrete syntax for Java in K, and then have the external parser generate ASTs with the exact KLabels associated to your Java constructs in K.  But you know that already.  Then you can make your semantics look as beautiful as you want.

**Comment by traiansf** [comment]
Can you provide a small .k file exhibiting the problem?

2014-03-30 14:26 GMT+03:00 Grigore Rosu notifications@github.com:

**Comment by denis-bogdanas** [comment]
You are right Grigore about the additional wrapper. When we define something like
syntax KListWrap ::= "[" KList "]" (klabel(Foo))

It ends up producing terms like 
'Foo(KList2KLabel ('Bar(...),,'Baz(...)) (.KList))

I ended up using the following:

syntax KLabel ::= "'ListWrap"
rule 'ListWrap(Ks:KList) => [Ks] [structural, anywhere]

syntax KListWrap ::= "[" KList "]"
rule [S1:K,, Stmts:KList] => S1 ~> [Stmts] [structural]
rule [.KList] => .K [structural]
