### ISSUE TITLE
Built-in module names cannot be used in user programs

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#34]
krun fails to run user programs that have a module named same as one of the built-in modules. This can be a problem for a name like "builtins" because IMO it's a very generic name and some users may want to use in their K programs.

```
Warning: Compiled definition file name (builtins) and the extension of the program () aren't the same. Maybe you should use --syntax-module or --main-module options of krun
Warning: Maude produced warnings or errors.
Advisory: redefining module BUILTINS.
```

**Comment by dwightguth** [comment]
We are likely not going to fix this because it affects only the maude backend and the maude backend is eventually going to go away entirely. In fact, we have not done significant development on the maude backend in quite some time. Therefore, in the interests of keeping the issue tracker clean enough to be usable, I am closing this.
