### ISSUE TITLE
Constructors for KList

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#345]
KList currently has a KList(KList) constructor (https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/kil/KList.java#L37).  We would like to add a KList(Term ...) constructor but these overlap when the argument is a single KList. We need to find a way to handle both.

(Note that the parent of KList also has a copy constructor so just removing the KList(KList) constructor does not work.)

**Comment by andreistefanescu** [comment]
Add static methods for constructing a KList from an array of elements. You may also want to remove completely the constructors of the form T(T) and replace them with a clone method.

**Comment by grosu** [comment]
Guys, something seems fishy here.  We should have no constructors for KLists at all.  The data-structure KAST should be a mirror of the textual KAST, so since we have no constructors for KLists in the latter we shouldn't have any in the former either.  Or are we talking about different things?

Grigore

**Comment by andreistefanescu** [comment]
We are talking about java constructors here.
