### ISSUE TITLE
unified-builtins2 --- Maude backend's cooling seems to be broken

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#350]
I think it is simplest to just copy and paste

```
fslwork$ pwd
/home/grosu/github.grosu/k/samples/java_rewrite_engine/tutorial/1_k/2_imp
fslwork$ kompile imp.k
fslwork$ krun ~/github.grosu/k/tutorial/1_k/2_imp/lesson_1/tests/collatz.imp
<T>
    <k>
        notBool (m <= 2) ~> if ( HOLE ) { { n = m ; m = (m + -1) ; while (
           (! (n <= 1)) ) { s = (s + 1) ; q = (n / 2) ; r = ((q + q) + 1) ; if
           ( (r <= n) ) { n = (((n + n) + n) + 1) ; } else { n = q ; } } } 
          while ( (! (m <= 2)) ) { n = m ; m = (m + -1) ; while ( (! (n <= 1))
           ) { s = (s + 1) ; q = (n / 2) ; r = ((q + q) + 1) ; if ( (r <= n) )
           { n = (((n + n) + n) + 1) ; } else { n = q ; } } } } else { }
    </k>
    <state>
        m |-> 10
        n |-> 0
        q |-> 0
        r |-> 0
        s |-> 0
    </state>
</T>
fslwork$ kompile imp.k --backend=java --smt=none
fslwork$ krun ~/github.grosu/k/tutorial/1_k/2_imp/lesson_1/tests/collatz.imp --backend=java --smt=none
[4481, 1.228 s]
<T>
    <k>
        .K
    </k>
    <state>
        m |-> 2
        n |-> 1
        q |-> 1
        r |-> 3
        s |-> 66
    </state>
</T>
fslwork$ 
```

**Comment by radumereuta** [comment]
I think I know what happened here.
If you guys remember when I did the sort type inference for variables last summer, I've split it into two parts. One for maude, and one for java. Why two? Because doing full concrete sot inference for maude created problems (performance for one, but I also think it broke it in some way.. can't remember exactly).

More details about what happens:
rule I1 + I2 => I1 +Int I2
For the java backend the inferred sorts are `Int`, but for maude are `K`

The simplest fix for this would be to use the 'expectedSort' field from variables instead of 'sort'. If that works, I could go into the type inferencer and remove the part which computes the sorts for maude.

**Comment by grosu** [comment]
I think there was a different problem, I did not switch to the right unified-builtins2 branch.  Once I switched, it suddenly worked.  We should definitely avoid having different results in different backends for the same programs/definitions.  We need to include these as tests in ktest.

**Comment by dwightguth** [comment]
@traiansf can you take it as a todo to make sure that all the examples that work for the Java Rewrite Engine are tested in the unified-builtins branch using the same definitions, programs, inputs, and outputs? Because I'm not sure that level of testing has been done yet, and without that, we have no guarantee that merging the branch will actually be safe.

**Comment by radumereuta** [comment]
Ah @grosu, ok. But I agree with @dwightguth, we need tests that verifies that both backends work correctly.

**Comment by traiansf** [comment]
Well, I would.  The problem now is that since your recent merge the Java
backend stopped working.  Once I get it working again, I'll set up the
tests.

2014-04-10 21:02 GMT+03:00 dwightguth notifications@github.com:
