### ISSUE TITLE
Id constants parsed in two different ways

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#39]
Let us consider the following definition:

```
module TOK-SYNTAX

  syntax Exp ::= Id "(" Id ")"

endmodule

module TOK
  imports TOK-SYNTAX

  syntax Id ::= "a" | "b" | "c"

  rule a(b) => a(c)

  configuration <k> $PGM:Exp </k>
endmodule
```

If this is compiled and the executed on the program "a(b)" then  the result is 

```
<k>
    a ( b )
</k>
```

and not

```
<k>
    a ( c )
</k> 
```

as expected. The reason is given by the fact that the rules is compiled as

```
eq <_>_</_>(k, _~>_(_`(_`)('_`(_`), _`,`,_(_`(_`)('a, .KList), _`(_`)('b, .KList))), GeneratedFreshVar0:K), k) = 
<_>_</_>(k, _~>_(_`(_`)('_`(_`), _`,`,_(_`(_`)('a, .KList), _`(_`)('c, .KList))), GeneratedFreshVar0:K), k) 
[metadata "filename=(/Users/dlucanu/teste-temp-k/tokens/tok.k) location=(12,3,12,19) computational=()"] .
```

and the program is parsed as 

```
_`(_`)('_`(_`), _`,`,_(_`(_`)(#token("Id", "a"), .KList), _`(_`)(#token("Id", "b"), .KList)))
```

Note that the Id constants have different representations: in the rule a labelled form and in the parsed program is a token.

If the syntax declaration

```
  syntax Id ::= "a" | "b" | "c"
```

 is moved in the syntax module, then it works, but I am not sure that this the right solution.

Now there are several definitions broken (some of them belong to our collaborators from France) and it took me a while to figure out this behaviour.

I cannot see a clean solution now. May be we should discuss this in the next meeting.

**Comment by radumereuta** [comment]
I know of this problem.
It started when #Id got removed.
When I generate SDF, I have a step where I collect all the productions that should become a token.
In the old version I would just simply check to see if the sort has a # in front of the sort name, but now we don't have that.

In fact this problem was a recent thread on the k-list, and the closest we got to a new solution is that if you declare a token for a specific sort, let's say:
  syntax Id ::= Token{...}
then, that sort becomes a lexical sort, and every single terminal declared of that sort, would also become a token/constant.

Also productions like:
  syntax Id ::= String2Id( String )
are still valid.

If everybody is in agreement with this implementation, and if this is urgent, I could find some time this week to implement it, although, untill next week, I'm pretty booked.

**Comment by dlucanu** [comment]
There is an another place where the Id constants are parsed  in a different way.
If we compile the definition

module TOK

  syntax Exp ::= Int

  configuration <k> $PGM:Exp </k>
endmodule

with the option "-symbolic" and parse the program "#symInt(a)" then the result is

$ kast test.tok
_`(_`)(#symInt, _`(_`)(#token("#Id", "a"), .KList))

Note the use of the sort "#Id". This broken the translation of the formulas to SMTLIB.

**Comment by radumereuta** [comment]
This has been fixed.
