### ISSUE TITLE
is there a bug in ktest --generate-out parameter?

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#391]
While reading an unrelated commit I realized that there may be a bug with ktest's `--generate-out` handling.

First, I made some experiments and I never managed to make ktest generate a new output file instead of updating current one. Here's what happens:

When `--generate-out` is passed:
- If output file is missing, it's generated (as expected)
- If output file is there, but contents does not match with program output, same file is updated (I think this is a bug)
- If output file is there, but contents match, nothing happens (again expected)

To me, second case should be "If output file is there, but contents does not match with program output, a new output file is generated with program output written in it (but old file should not be updated since we're in _generate_ mode, not in _update_ mode)".

Also, I don't understand how new output file name generation supposed to work. It seems like that `TestCase.getNewOutputFilePath` works wrong. I run an example and for this output file:

```
/home/omer/K/k_new_dist/k/tutorial/1_k/1_lambda/lesson_1/tests/free-variable-capture.lambda.out
```

it returned this new output file:

```
/home/omer/K/k_new_dist/k/tutorial/1_k/1_lambda/lesson_2/tests/free-variable-capture.lambda.out
```

Notice the difference in the parent directory. I think this is also a bug.

@daejunpark Can you help me with this?

(related commit 9bdc321 I couldn't find a pull request for this -- this patch was probably not reviewed)

**Comment by grosu** [comment]
Daejun, I remember we discussed all these cases long time ago, when you worked on this problem.  Also, I remember at the time I asked you to write this up in the manual draft, precisely to have it documented when situations like this arise.  Can you please intervene here and clarify things for Omer and us?  Also, in case this is not described in the manual, can you please do it?

Thanks,
Grigore

**Comment by daejunpark** [comment]
@osa1 @grosu 
This is an intended behavior. I'll describe the detail in the manual draft soon, and let you know again.

**Comment by daejunpark** [comment]
I described the behavior of the two options of `--update-out` and `--generate-out` as follows. @osa1 Could you please read it and let me know if this explanation clarifies your experiments?

---

Automatic output generation

ktest has a feature of automatic generation of output (*.out) files. This feature consists of two options: `--update-out` and `--generate-out`.

`ktest --update-out`

When this option is enabled, ktest updates every output files by newly generated output of krun. This option creates a new set of reference output files, discarding the previous one. This option is useful when you want to totally change the format of output files, especially due to the version update of krun.

Use this option at your own risk. With this option, ktest does not check the correctness of krun’s output at all.

`ktest --generate-out`

When this option is enabled, ktest generates a new output file at a new place whenever krun’s output is different from the existing output file. The new output file is created in the last directory of the given `results` attributes.

This option is useful when you create a new K definition and want to construct a new set of test programs and outputs for the K definition.

NOTE:
- A new output file is also created when no previous output file exists.
- A previous output file could be updated if the last directory of the `results` attributes is the same with the directory that the previous output file resides.

NOTE:
These two options make ktest run in sequential mode, ignoring the `--threads` option of ktest. Since multiple tests can share a single output file, generating/updating output files should be done sequentially. Otherwise, parallel updates may cause a race condition for the shared output files.

**Comment by osa1** [comment]
Thanks @daejunpark , I'm closing this issue since apparently the implementation does not have any problems and the behavior is intended. :+1:
