### ISSUE TITLE
No support for equality of Bag

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#508]
In the k-equal.k file, I cannot see the "==Bag" operator being defined. This operator is very important in defining C semantics. The original C semantics had its own definition of this operator. Basically, it turned "==Bag" operator into "==K" operator. However, this solution does not work now. I think we should have a backend definition for the operator "==Bag".

**Comment by yilongli** [comment]
@andreistefanescu We don't even have `bag.k` in the `include/builtins` directory any more. Should I recover `bag.k`, define the `==Bag` operation only, and hook it to the term equality implementation in the Java backend?

**Comment by liyili2** [comment]
I thought all "==" operators are defined in k-equal.k

**Comment by dlucanu** [comment]
This is a general remark regarding the equality: I noticed that the new definitions in unified builtins use the predicate =K. If I correctly remember, the convention is to use =Sort for the semantic equality (the equality in the domain) and ==Sort for the syntactic equality (equality of terms reduced to normal forms using function and anywhere rules).
For instance, if Loc is the sort for symbolic locations then I have to add something like
rule L1:Loc =K L2:Loc => L1 ==K L2
in order to say that the semantical equality is the same with the syntactic one. This allows to evaluate predicates of the form "notBool  L:Loc in keys(Store:Map)".
If the above remarks are true, then we should have defined =Bag, =Map, =Set ... for builtins.

**Comment by andreistefanescu** [comment]
Since Bag is one of the few sorts not subsorted to K, the ==Bag has to be explicitly declared (maybe in k-equal.k).

**Comment by dwightguth** [comment]
Fixed #638
