### ISSUE TITLE
Rewriting Set to .K

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#583]
```
dwightguth@rvwork-1:~/test$ cat test.k
module TEST

configuration <set> SetItem(5) </set>


rule <set>... SetItem(5) => .K ... </set>

endmodule
dwightguth@rvwork-1:~/test$ kompile test.k
dwightguth@rvwork-1:~/test$ krun
<k>
    .K
</k>
<set>
    K2Set(.K)(.KList)
</set>
dwightguth@rvwork-1:~/test$ krun --search
Search results:
No search results
```

This rule compiles in the maude backend to this strange behavior. I'm not quite sure what the correct thing to do in this case is, but I thought I'd report this since it seems like this is wrong, especially because this term in Maude is not well-sorted, but is a kind (which is why search returns no results).

**Comment by radumereuta** [comment]
I think this is forbidden in the java backend. Maybe we should run the same check for maude too?
@andreistefanescu @yilongli, what do you think?

**Comment by andreistefanescu** [comment]
I'm not sure what "..." without a cell even mean...

**Comment by grosu** [comment]
DEFINITELY!  We should have the same checks in all backends.  If a particular backend needs a specific limitation for some reason, then that should be clearly mentioned and printed to the user (For example: Coq backend does not support associative matching.).

Grigore

**Comment by dwightguth** [comment]
@andreistefanescu sorry I accidentally forgot to markdown-escape the code.

**Comment by andreistefanescu** [comment]
Yeah, this should not work. We need an error message for it.

**Comment by traiansf** [comment]
@radumereuta shouldn't this be checked at parse time? The fact that one uses ... means that the intended sort is the one declared in the cell, which is set.  therefore .K cannot be used there as this is not valid KIL

**Comment by radumereuta** [comment]
Well, it is checked. But K is an exception everywhere, meaning you can replace any sort with a K term, and you can put anything in a place where you expect a sort. This is why the labeled form works:
K ::= KLabel "(" KList ")"  // this being the KApp
1 + '_+_(2, 3) works because I can put K in the right hand side of + where I would expect an Exp, and I can put 2 and 3 inside of the KApp, because Int is a subsort of K.

You are having this problem now, because Set is now a subsort of K, whereas before they were disjoint sorts, and I could do more type checking.
