### ISSUE TITLE
linear algorithm to compute minimal upper bounds and maximal lower bounds in Poset

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#652]
Can be done by doing a topological sorting first. Assigning it to myself. Will get to it sooner or later.

**Comment by radumereuta** [comment]
We already have an implementation of Tarjan's algorithm for topological sorting.
I think we should revisit the algorithm that we have in utils.algorithms.SSCTarjan and make it more general so we can use it in all cases.
Traian also needed such an implementation for 'pdmc' branch. So it's worth it to unify the implementations.

**Comment by dwightguth** [comment]
Tarjan's algorithm actually computes strongly connected components. Since we now have both the Tarjan algorithm, which cannot be replaced with a Topological sorting algorithm since it does something distinct, and the topological sorting algorithm I created in the pull request that is currently out, I will close this. We can easily compute lub and glb in scala using these tools.
