### ISSUE TITLE
krun --- exception thrown instead of error message

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#67]
fslwork$ pwd
/home/grosu/k/dist/tutorial/2_languages/1_simple/1_untyped/programs/threads
fslwork$ krun threads_01.simple -d ../../simple-untyped.k
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.krun.Main.execute_Krun(Main.java:975)
    at org.kframework.main.Main.main(Main.java:59)
fslwork$

**Comment by daejunpark** [comment]
Thank you, Omer. Inspired you, I implemented a more general fix.

Now it was fixed for all of ktools. 4f991dd0ae2bf32efc713e4989483b0645a6b9b1

**Comment by osa1** [comment]
Good idea.

@Daejun, not sure if intentional but you also committed your editor
settings:
https://github.com/kframework/k/commit/4f991dd0ae2bf32efc713e4989483b0645a6b9b1#diff-11c0fc2d69692786f2721f6c24fee3ceR233

https://github.com/kframework/k/commit/4f991dd0ae2bf32efc713e4989483b0645a6b9b1#diff-5deccf38e99a7824cbd1e7fd766c03e6R65
or
is it because this file has tabs and you want from vim users to override
their settings so that no tab/space mix happens?

---

Ömer Sinan Aðacan
http://osa1.net

2013/10/9 Daejun Park notifications@github.com

**Comment by daejunpark** [comment]
@osa1 Yes, it is intentional. Because of exactly what you explained. Please let me know if it can be a problem.
