### ISSUE TITLE
`_` is deprecated in Java 8

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#679]
Many `*Visitor` classes use underscore as a variable name. I really like it but, unfortunately, 

> use of '_' as an identifier might not be supported in releases after Java SE 8

We'll have to get rid of it, at least in order to get rid of the warnings.

(cc @dwightguth)

**Comment by osa1** [comment]
I don't like our use of underscores here, because even though `Void` arguments do not have any value, they're not ignored. Sometimes passed to other methods as arguments, and returned. So I think we should give them proper names, at least `v` or something short like that, and keep underscore for "ignoring".

If we still want underscores, something like this might help fixing those warnings:

```
$ find . -iname "*.java" | xargs sed -i "s/_)/__)/g"
```

**Comment by cos** [comment]
it seems to have been fixed in the meantime.
