### ISSUE TITLE
problem with combination of #if and String2Float

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#70]
issue.k:

module ISSUE

syntax K ::= "toFloat" "(" String ")"

rule toFloat(Str:String) => #if (lastChar(Str) ==String "F")
                              #then Str
                              #else String2Float(Str)
                            #fi

syntax K ::= "lastChar" "(" String ")"                                  [function]
rule lastChar(Str:String) => substrString(Str, lengthString(Str) -Int 1, lengthString(Str))

endmodule

test.issue:

toFloat("1.1F")

expected output:
<k>
   "1.1F"
</k>

actual output:

<k>
    '#if_#then_#else_#fi(
      _`,`,_(_`(_`)(#_(true),.KList),_`(_`)(#_("1.1F"),.KList),_`(_`)(#_(string2Float("1.1F")),.KList))
      )
</k>

**Comment by denis-bogdanas** [comment]
Confirmed on latest K : 9f65cd7

**Comment by traiansf** [comment]
It should work now.  Dwight had added the right code to transform String2Float into a hook (since it is partial), but there was an issue with the naming of the hook and it was transformed without checking whether the result is a float, which messed everything up.

I'm closing it, but feel free to reopen it if any side-issues arise.

**Comment by denis-bogdanas** [comment]
Yup, it works now. Thanks.

**Comment by denis-bogdanas** [comment]
Please move the directory issue70 from issues to regression.

**Comment by dwightguth** [comment]
Oncall should add this test to regression.k like Denis suggested.
