### ISSUE TITLE
ktest -- different behaviors between the definition option and programs/results option

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#704]
Let's say I want to call ktest under directory `k` to run the regression test suite using the following command:
`./bin/ktest tests/configjavarw.xml --skip pdf -v --threads 1`

The `configjavarw.xml` has to be written like this to allow ktest to correctly find the directories:

```
<tests>

  <test
      definition="tests/regression/java-rewrite-engine/cell_map/test.k"
      programs="regression/java-rewrite-engine/cell_map"
      results="regression/java-rewrite-engine/cell_map"
      skip="pdf"
      extension="test"
      >
    <kompile-option name="--backend" value="java" />
    <all-programs>
      <krun-option name="--smt" value="none" />
    </all-programs>
  </test>

</tests>
```

Note that definition option starts with `tests`, while programs/results option starts with `regression`. Is this the expected behavior of ktest? @osa1 Thanks.

**Comment by osa1** [comment]
This is expected behavior.
- `definition` field is appended to current working directory to get absolute path of definition file.
- `programs` and `results` fields are appended to test config file's directory by default to get absolute paths of programs and results folders. If `--programs` or `--results` command line arguments are specified, then `programs` and `results` fields are appended to respective command line arguments.

So you need to either provide `--programs . --results .` argument or use paths relative to _config file's directory_ for `programs` and `results` fields.

**Comment by yilongli** [comment]
Thanks for the explanation.
