### ISSUE TITLE
PDF backend moves rules after comments following them

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#73]
If you have a formal annotation comment  after a rule, then for some reason the rule is moved after the comment.  This ends up making the PDF posters confusing.  See, for example, kool-untyped.pdf

**Comment by grosu** [comment]
Traian, this is probably an easy to fix bug.  We had it before, too, but we managed to get rid of it.  It is strange that it resurfaced.  Or maybe it has something to do with parsing?

**Comment by traiansf** [comment]
I think it is related to parsing.
When it gets to the LatexFilter, everything is already ordered in some way.

Radu used to parse comments separately (because of parsing issues), then
integrated them into the parsed module.  During that integration, if line
numbers are not consistent, some are displayed in the wrong order.

Maybe it is related with the recent work on simple parsing?

best wishes,
Traian

2013/10/9 Grigore Rosu notifications@github.com

**Comment by grosu** [comment]
Guys, can you please fix this bug?  It should be simple to fix for you, and it would increase the user's K experience a lot, at least during my classes (I teach using the PDF posters).  Typical "low hanging fruit".

**Comment by radumereuta** [comment]
I managed to trace this issue back to the new Basic Parser. Michael, can you have a look? Probably it's not a very difficult thing.
