### ISSUE TITLE
klabel attribute changes the semantics of programs

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#739]
Let us consider the following definition:

```
module TEST
 syntax A ::= Id [klabel(a)]
 syntax B ::= Id [klabel(b)]
 syntax String ::= A2String(A)  [function]
 syntax String ::= B2String(B)  [function]
 rule A2String(X:Id) => Id2String(X) +String ":A"
 rule B2String(X:Id) => Id2String(X) +String ":B"
 syntax Exp ::= A | B | A "+" B
 syntax String ::= Exp2String(Exp) [function]
 rule Exp2String(X:A) => A2String(X)
 rule Exp2String(X:B) => B2String(X)
 rule Exp2String(E1:A + E2:B) => Exp2String(E1) +String " + " +String Exp2String(E2)
 rule E:Exp  => Exp2String(E)
endmodule
```

If we execute it on the program "a+b" then we get the following output:

```
<k>
    A2String ( a ) +String " + " +String B2String ( b )
</k>
```

If we remove the klabel attribute from the production of A and resp. B, compile and execute the new compiled definition on the same program, we get a different ouput:

```
<k>
    "a:A + b:A"
</k>
```

Obviously, none of the two outputs is the one expected: "a:A + b:B". Is it any way to get the right behaviour?

**Comment by radumereuta** [comment]
Running krun with --output raw, presents a few more details:
< k > '_+String_('_+String_('A2String(a(#token("Id", "a")(.KList))),,# " + "(.KList)),,'B2String(b(#token("Id", "b")(.KList)))) </ k >

The problem in this case is that the label for the two subsorts are not handled , and the computation gets stuck. So we need two rules to handle the labels.

The second issue is that "a" is not recognized as a klabel. Using klabe('a) instead would be able to be matched by the general lexer rule for klabels (quote followed by almost anything).

I will leave this opened since we don't have a manual.

**Comment by dlucanu** [comment]
Thanks Radu. Here is the definition that produces the right behaviour with the actual implementation (it could be used in the manual):

```
module TEST
 syntax A ::= Id  [klabel('a)]
 syntax B ::= Id  [klabel('b)]
 syntax String ::= A2String(A)  [function]
 syntax String ::= B2String(B)  [function]
 rule A2String('a(X:Id)) => Id2String(X) +String ":A"
 rule B2String('b(X:Id)) => Id2String(X) +String ":B"
 syntax Exp ::= A | B | A "+" B
 syntax String ::= Exp2String(Exp) [function]
 rule Exp2String(X:A) => A2String(X)
 rule Exp2String(X:B) => B2String(X)
 rule Exp2String(E1:A + E2:B) => Exp2String(E1) +String " + " +String Exp2String(E2)
 rule E:Exp  => Exp2String(E)

endmodule
```
