### ISSUE TITLE
Cannot recognize klabel option properly in Java Backend 

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#761]
When I have the following set of rules:

```
module TEST

     syntax KItem ::=  "start"

     syntax Type ::= "int"
     syntax SymBase ::= String

     syntax SymLoc ::= loc(SymBase, Int, Set)
     syntax SymLoc ::= loc(SymBase, Int)  [klabel('locs)]
     syntax LValue ::= lv(SymLoc, Type)
     syntax Value ::= lval(SymLoc, Type)

     rule start => lv(loc("abc",1),int)

     rule lv(L:SymLoc, T:Type) => lval(L, T)
          [structural]

endmodule

```

If I run the program "start", Java backend will have the output:

```
<k>
    lv ( 'loc("abc",, 1) , int )
</k>

```

while Maude backend will have the output:

```
<k>
    lval ( loc ( "abc" , 1 ) , int )
</k>

```

If I delete the klabel attribute, the Java backend will run properly:

```
<k>
    lval ( loc ( "abc" , 1 ) , int )
</k>
```

**Comment by grosu** [comment]
This is definitely a super-bug.  I actually wander how such a bug can even be possible, so I would be really curios to know what happened here.

Thanks,
Grigore

**Comment by yilongli** [comment]
Unable to reproduce the bug in the latest unified-builtins2 branch. You probably forgot to delete the `*-kompiled` directory so that the parser still uses the out-dated cached parsing result. This is an known problem of the parser, which is not able to invalidate the cache when the attribute of a rule has changed.

**Comment by liyili2** [comment]
Yes. It is because of the cache problem I mentioned before. Update some info about this:

If I declare a constructor as:

```
syntax ABC ::= "abc" "(" K ")"
```

Then, I compile the definition, and then I delete the quotation marks. The evaluation will get stuck at the place when it is going to evaluate the term abc(K).

```
syntax ABC ::= abc(K)

```

**Comment by grosu** [comment]
What's the reason for which the parser cannot invalidate the cache when the attribute of a rule has changed?  That does not look like a compromise that we should make ...

Grigore

**Comment by yilongli** [comment]
I don't know the details but @cos will take care of it.

**Comment by grosu** [comment]
@cos?  I thought that was @radumereuta 's territory.

**Comment by yilongli** [comment]
https://github.com/kframework/k/issues/721
https://github.com/kframework/k/issues/697

**Comment by cos** [comment]
I assigned myself the task of adding a "--clean-cache" (or similarly-named) option which deletes the cache. In the meantime, simply delete the `*-kompiled` directory when something goes wrong. In #697 @radumereuta argued it would be better for caching to be disabled by default. It may be a good idea considering it keeps creating problems. I think a very simple solution for most problems would be to timestamp the caching, and invalidate the cache if any of the original files has a later _modified_ date. @radumereuta, how hard would that be?

**Comment by grosu** [comment]
But why is this a problem at all?  Don't we have a kast version of a definition, which contains everything, which can be used for deciding when anything changed?  If we don't, then we have a bug/problem in how we handle kast, which needs to be fixed.  We have just wasted too much time in this project by patching things instead of solving them at the root.

Grigore

**Comment by radumereuta** [comment]
@cos time stamps won't really work, because if you change a rule, the file will change, but that doesn't mean you have to invalidate the parser, or all the parsed rules.

@grosu we don't use kast to compare. At the moment we use two things to invalidate the cache:
1. invalidate the parser. I'm comparing the SDF file from the previous run, with the generated SDF files from the current kompilation. This is a safe way to invalidate the parser, since I'm comparing exactly the input sent to sdf2table.
2. invalidate the cached rules. We do this right now by saving the original string (what I'm sending to the parser) and the resulting AST. Each node in the AST saves a reference to the original syntax declaration, so I know how to flatten it later. It's really important to do this really early because consecutive runs of kompile has to behave in the same way; report the same error messages, the same warnings that my appear during kompilation. The problem here is, that when I'm restoring a parsed rule from cache, it points to the old production, which will not have the current changes (like adding a new klabel). I don't know any clean way of invalidating the cache in this case. @cos felt more confident about this, this is why the issue has been reassigned.

I hope this answers a few more questions.

**Comment by cos** [comment]
> The problem here is, that when I'm restoring a parsed rule from cache, it points to the old production, which will not have the current changes (like adding a new klabel). I don't know any clean way of invalidating the cache in this case.

I don't understand how this works. Still, is there a safe way of making this choice, even if the cache is invalided more often than optimal?

> @cos felt more confident about this, this is why the issue has been reassigned.

I'm confident that the advantage gained by caching is worth the trouble of manually cleaning up the cache from time to time. And we should have a clean solution by the time we cut another release.

**Comment by radumereuta** [comment]
I'm not sure. I wonder if It is possible to print the klabel to the SDF file.
I think this would solve a part of the issue, because the cache invalidation would be done at the same time with the parser. This means the entire parser would be invalidated more often but it would be safer.

**Comment by grosu** [comment]
But why do you even go to SDF for cache invalidation?  You already did the flattening, so you already have all the grammar in one place, including all the attributes of all the productions.  Why not just store that, even as a string, and then check the new grammar, also as a string, with the old one, and invalidate the cache if they are different?  Then you can also reuse that with the new parser.  I think it is a strategic mistake to make it depend on the translation to SDF.
