### ISSUE TITLE
New error in new version of Kompile in type checking

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#795]
If I have this set of rules:

```
module TEST

     syntax Int ::= offset(SymLoc) [function]
     syntax SymLoc ::= SymVal
     syntax SymVal ::= "symVal"
     syntax CSize ::= SymVal
     rule offset(symVal) => symVal::CSize

endmodule
```

In the unified-builtins2 version of Kompile last Monday, it works fine. However, it doesn't work in the new version and it will return an error message as:

```
[Error] Critical: type error: unexpected term '(symVal )' of sort 'CSize',
expected sort 'Int'.
    File: /home/qangel/project/k-unified/bin/test.k
    Location: (9,29,9,42)
    Compilation Phase:
org.kframework.parser.concrete.disambiguate.TypeSystemFilter2

```

**Comment by radumereuta** [comment]
Yes... this is because I changed the semantics of casting. Now it tries to match productions which have been defined with exactly the sort of the cast.

If you write something like this: `rule offset(symVal) => symVal::SymVal` it would stop complaining about casting, but will cry because of something else:

```
[Error] Critical: type error: unexpected term '(symVal )' of sort 'SymVal', expected sort 'Int'.
        File: d:\work\k\samples\test\test.k
        Location: (7,29,7,43)
        Compilation Phase: org.kframework.parser.concrete.disambiguate.TypeSystemFilter2
```

This is because when you rewrite a function, you need to have decreasing sorts. Meaning that if you have Int in the left hand side, you must have Int or something subsorted to it. You can cheat this check by using cast again:
`rule offset(symVal) => symVal:>Int`
This means that inside the cast you can have anything subsorted to K, but on the outside, the term will be viewed as an Int.
I will not close this yet, since I'm trying to figure out if we really need this type of casting.

**Comment by liyili2** [comment]
What should I do? Should I just use symVal:>Int ??

**Comment by radumereuta** [comment]
If that solves your issue for now, yes.
I think I'm going to keep the current semantics for the current version of the parser, and we can rethink this when we have the new one, so I'm going to leave this opened as a reference.

**Comment by liyili2** [comment]
The new type checker will cause me to spend at least one or two weeks to fix all the type problems in C semantics.

**Comment by grosu** [comment]
Why?  Can you elaborate?  You should first make sure you do understand how the new type checker works, and the reason why the change was needed.

Grigore

**Comment by liyili2** [comment]
```
 syntax Constant ::= StringLiteral
 syntax IntConstant ::= Constant
 syntax Constant ::= TypedValue
 syntax Expression ::= Value
```

I need to add ths set of subsort relations in C semantics and I need to check whether or not these chances will cause any trouble in other rules. If it is, I need to find a way to rewrite those rules. One or two weeks' working is fine for me.

**Comment by liyili2** [comment]
In addition, I can do the check and rewrite only if the bugs I submitted are fixed.

**Comment by grosu** [comment]
Liyi,

I think you misunderstood me.  My concern is that you may do the wrong thing, and waste a lot of time doing some boilerplate work that does not make the semantics any better or cleaner.  I propose that you speak with Radu tomorrow to make sure you and him are in agreement as of what you should be doing, based on how the new parser works.  Then I'd like to understand that, too.

Grigore

**Comment by liyili2** [comment]
Ok. I can do it. 

Radu, I will have a doctor appointment tomorrow morning. I will go to Seibel to find you after the doctor appointment.
