### ISSUE TITLE
kv3.4---unnecessary .k folder 

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#798]
If I run `kompile` in some folder, without any arguments, it creates a `.k` folder.  On Unix that may be OK, because it is not visible, but on Windows that looks strange.

**Comment by osa1** [comment]
Main problem: kompile front-end can't know if selected back-end needs .k so it generates it anyway.

Kompile front-end is generating a .k directory and inside it a temporary file, for back-ends. Back-ends then just assume those files exist and use them.

Temp file is removed when kompile is terminated, but .k directory is not because I think it may have some files that may be reused in later invocations of kompile. (otherwise why not just remove the whole .k?)

I have two ideas in mind to solve this:
- Easiest solution: Just remove .k if it's empty after removing the temp file.
- Let each back-end generate .k and whatever temporary files they need, instead of generating them in front-end and assuming they're generated in back-ends. If we do this then we can delay generating .k directory until the back-end really needs it.
- Implement an API for .k and temporary file operations and internally make sure that files are only generated when needed. For example, create .k only when a write method is called. After program terminates, check if .k only has a temporary file and in that case remove the whole directory.

@dwightguth any other ideas?

**Comment by dwightguth** [comment]
You should be able to change the code to delete the temp folder so that it
deletes the .k folder instead. There is nothing left if that folder which
is not transient.
