### ISSUE TITLE
Tokens versus constant AST nodes

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#817]
Currently, if you write this production in a C-like language

```
syntax Id ::= "main"
```

in your semantics module, e.g., because you want to give special semantics to the "special" token `main`, then the current implementation will transform the current AST nodes corresponding to term `'main(.KList)` appearing in the semantic rules into the token term `#token("main","Id")`.

This has several problems:
1) It is complex and adds unnecessary kompilation time (one has to non-locally process the entire definition, going through all the rules in all the module)
2) It is non-modular and error-prone (you have to make sure you do this only for sorts which have Token productions on them; this, e.g., invalidates existing KAST versions of modules if one decide to add a Token production to a sort in a later module).
3) The resulting definition is slower than it should be, because indexing cannot take advantage of the fact the generated tokens are special AST constants, it will have to treat them as ordinary tokens, so no optimzations can be made for them.

There is a very simple alternative.  Instead of translating `'main(.Klist)` into `#token("main","Id")`, do it the other way around, simply by adding the following macro rule:

```
rule #token("main","Id") => 'main(.KList)   [macro]
```

No rules and no modules need to be touched.  As an optimization (to reduce the kompile time only, because macros will eventually be applied statically) we can add rules like above _only_ when the `main` constant can be parsed as a token using the regex'es defined with any of the Token productions of the corresponding sort.  This way, we do not add unnecessary rules like above for "temporary" constants.  Remember, for example, the `$1` and `$2` variables that we added to desugar multi-dimensional arrays to uni-dimensional ones in SIMPLE, KOOL, etc.  There is no need to add the rules

```
rule #token("$1","Id") => '$1(.KList)   [macro]
rule #token("$2","Id") => '$2(.KList)   [macro]
```

**Comment by radumereuta** [comment]
It is assigned to me, but it is expected of the main developers to say their opinion, because it involves the design of Kast, and how the parser should behave.

**Comment by traiansf** [comment]
It seems reasonable;  however, I'm concerned that we would now have two kinds of `Id`s: ones which are tokens, and ones which are more involved `KItem`s.  This would make for harder generic visitation of `Id`s, since one would have to distinguish which is which.

Moreover, this would imply a more complex logic for operations on `Id`s like
`Id2String` and `String2Id`.
Note that, since you assumed the `rule #token("main", "Id") => 'main(.KList)` is a macro,
then one could not apply it at runtime for `String2Id`, thus requiring to specialize `String2Id` at compile time for declared `Id`s.

In my view, any best solution to this problem would not distinguish between the representation of `main` and that of any other token of sort `Id`.

**Comment by grosu** [comment]
As I understand it from Radu, you can already add arbitrary productions to sorts that also have Token productions.  So we already suffer from the first problem that you mentioned, Traian.

`Id2String` : We need a general-purpose operation `Sort2String` that pretty-prints any term of sort Sort as a String.  This is something we discussed many times, I believe.  If that is true, then the first half of the second problem you mentioned will also have a more general solutions.

``String2Id` : Whatever we do now is wrong anyway, because we should normally check that the String indeed parses as an Id token using the regex provided with the Token productions, otherwise the operation should be undefined.  The correct solution here is, again, to have a String2Sort operation for nay sort, which would parse the String as an AST correctly following the given grammar.

I know it will take a while to make the above work propertly, but I believe that the above is the correct long-term solution, and that we are at a stage where we should aim for that.

Grigore

**Comment by dlucanu** [comment]
Isn't `Sort2String` somehow equivalent to `unparse` and `String2Sort` to 
`parse`?

Dorel

**Comment by grosu** [comment]
Yes!  The only difference is that one gives the sort as a parameter, while the other as part of the name; one can be thought of as a compiler and the other as an interpreter :)  But yes, since we want the #parse and #unparse to work well anyway, we should probably use these.

Grigore

**Comment by bmmoore** [comment]
I think the basic functionality we want here is allowing some particular values in a sort to be used in a definition, without adding the full token concrete syntax into the rule parser. Especially for types like builtin integers, it should be nicer for backends and so on if we go uniformly to the token rather than to a label.

Considering labels, as long as we allow productions like `Int ::= Int "+Int" Int` in sorts that have a token, it's more uniform if we can also get labels with no arguments instead of always converting them to tokens. If we want `main` to become a token, we already have a way to explicitly allow that with a token production like `Id ::= Token{main}`.  The only problem is that this adds a separate regular expression instead of checking that you are making one available.

So, I propose we add a new attribute "token" which makes `syntax Sort ::= "string" [token]` first check that `string` is accepted by some existing token, but otherwise acts like you declared `Token{string}`, and then `syntax Sort ::= "string"` can just get a label in the ordinary way.
