### ISSUE TITLE
ktest --- cannot test the same definition one multiple sets of program/results

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#84]
I need to test the same definition against different sets of programs/results.  Unfortunately, ktest simply discards the second test.  For example, when extending a type checker I need to still make sure that all the previous tests work (the first test below), while the new tests also work (second test below):

<tests>                                                                         

  <test
      definition="../simple-typed-static.k"
      programs="../../../../programs"
      extension="simple"
      results="../../../results" >
      <all-programs>
        <krun-option name="-pattern" value="&lt;tasks&gt;.Bag&lt;/tasks&gt;"/>
      </all-programs>
  </test>

  <test
      definition="../simple-typed-static.k"
      programs="../../../../2_dynamic/exercises/exercise_2/programs/"
      extension="simple"
      results="." >
      <all-programs>
        <krun-option name="-pattern" value="&lt;tasks&gt;.Bag&lt;/tasks&gt;"/>
      </all-programs>
  </test>

</tests>

Unfortunately, the second set of tests are not executed.  I need this bug fixed asap, because this config.xml file is handled to students in my class.

**Comment by daejunpark** [comment]
I temporarily fixed this problem and now wait for the regression test result.

Since this is urgent, I'm going to push this fix, but I want @andreiarusoaie take a look this, and fix this problem fundamentally.

What I did is: 

In the method Test.compareTo,

```
-        d = (this.hashCode() == (o.hashCode())) ? 1 : 0;
+        d = (this.hashCode() == (o.hashCode())) ? 0 : 1;
```

My concern is:

I found that this code came from the commit 9639fc16fbbaaf24c1f026a5f8992db3307a6bd9 (2 months ago),

```
-    d = this.programsFolder.compareTo(o.programsFolder);
+    d = (this.hashCode() == (o.hashCode())) ? 1 : 0;
```

But, I cannot understand the above change. And also, I don't know why you didn't as follows:

```
d = this.hashCode().compareTo(o.hashCode());
```

Probably, this is because I'm newbie of Java. Please let me know the things behind the scene. Thanks.

**Comment by grosu** [comment]
Thank you, Daejun!  It works for what I needed it, so solved my problem for now.  As Brandon suggested in our meeting today, this will be problematic when the two tests for the same definition require different kompile options.  Which is, btw, a quite plausible scenario.

**Comment by daejunpark** [comment]
In that case, we need to create different *-kompiled directories for each units. Probably, 'title' attribute exists for that.
