### ISSUE TITLE
ktest --- race on pdf generation

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#86]
This is an interesting one.  If you have more tests for the same definition, then you may end up with a race on the pdf generation :)  See below:

fslwork$ ktest config.xml 
Buildfile: config.xml
Kompile the language definitions...(2 in total)
Compiling 2 definitions
SUCCESS
Generating PDF documentation...(2 in total)
Generate pdf for 2 definitions

FAIL: /home/grosu/k/dist/tutorial/2_languages/1_simple/2_typed/1_static/exercises/exercise_2/programs/../simple-typed-static.k

Running /home/grosu/k/dist/tutorial/2_languages/1_simple/2_typed/1_static/exercises/exercise_2/programs/../simple-typed-static.k programs... (34 in total, 0 with input, 34 with output)
SUCCESS
Running /home/grosu/k/dist/tutorial/2_languages/1_simple/2_typed/1_static/exercises/exercise_2/programs/../simple-typed-static.k programs... (9 in total, 0 with input, 9 with output)
FAIL: ./ex01.simple
FAIL: ./ex02.simple
FAIL: ./ex03.simple
FAIL: ./ex05.simple
FAIL: ./ex08.simple

fslwork$ more config.xml 
<tests>

  <test
      definition="../simple-typed-static.k"
      programs="../../../../programs"
      extension="simple"
      results="../../../results" >
      <all-programs>
        <krun-option name="-pattern" value="&lt;tasks&gt;.Bag&lt;/tasks&gt;"/>
      </all-programs>
  </test>

  <test
      definition="../simple-typed-static.k"
      programs="."
      extension="simple" >
      <all-programs>
        <krun-option name="-pattern" value="&lt;tasks&gt;.Bag&lt;/tasks&gt;"/>
      </all-programs>
  </test>

</tests>

Most of the times it works fine.  It is only rarely that it fails to generate the pdfs.

**Comment by dlucanu** [comment]
A way to decrease the probability to have  a race is the use of fewer 
threads :)

Dorel

**Comment by andreiarusoaie** [comment]
For both this issue and `issue 84` (https://github.com/kframework/k/issues/84) I used the same solution in the past: compile in different directories. We were able to output the compiled (and the pdf) definitions into a specific location (using the -output option) computed using the 'title' attribute in the config.xml. Then, ktest passed the compiled definition to krun together with the tests.
Right now these options were completely removed from kompile (or I cannot find them anymore). Probably this is because we considered the java approach (only one compiled definition in a single folder) for kompile. If we want to keep that but also to run the tests for the same definition in parallel we have a few variants:

1) we kompile the definition only once by hand and we use the --skip option
2) we put back the -output option but this conflicts with our current convention of having a single compiled definition in the same folder
3) we detect in ktest if the compiled definition exists and we do not compile anymore; this may cause some problems: the definition is not compiled and two threads start to compile it in the same time, or an older version of the definition is compiled and we want to force recompilation - so it is not clear when to recompile with ktest
4) we implement an older mechanism we had in the past: compile first everything using fresh files and after the compilation is finished we rename the fresh files with their usual names. Even this solution may cause problems since the -compiled folder will always be replace by the last thread which finished compilation.

I'm most in favor of 1) because `ktest` is mostly used to test one definition. If you want to test the same definition with two different sets of programs you can compile/pdf it once and then skip these steps.

Another problem which remains open for me is that having a single compiled definition in the same directory where the K definition is will be a problem when we want to kompile more than twice the same definition with different compilation options in parallel. On the other hand, I think that compilation of a K definition with extra-options should not affect the programs which worked with a simple compilation (without any options). Are there any situations like this? To be more explicit, if I compile the definition normally:
`kompile def.k`
and I can run all programs `P` then:
`kompile def.k --backend symbolic`
runs successfully all the `P` programs. Isn't this the case for all options?

**Comment by grosu** [comment]
Andrei, none of your solutions is fully satisfactory, because we really want to allow people to kompile the same definition with different options and then be able to test different program sets with different kompilations.

Also, I don't see how 2 has anything to do with this discussions!  You can use the new -d option to recreate the same use model of K like before.  We had lots of arguments about that before we made the mode.  For example:

  kompile def.k
  krun programs/pgm.def

versus

  kompile def.k -d clone
  krun programs/pgm.def -d clone

It is actually even simpler to use than before.

This also suggests what I believe is the best solution to handle this problem, because one can manually use the -d option to both kompile and krun in the second test:

Step 1) If a language definition appears twice with different kompile options but without different -d options, then issue an error: "Definition X tested twice, with different kompile options but with the same target directory.  To avoid race conditions on generated files, use a different kompilation folder (with the -d option both in kompile and in krun) for each test of the same definition which has different kompile options."

Step 2) Then collect a SET, and not a list, of kompile commands.

Grigore

**Comment by grosu** [comment]
I would like to revive this issue, because I belive that this is the right solution.  Andrei A, if you are busy with other urgent things, then Daejun can help implementing it.  Please let us know how you prefer to proceed here.  Here is again my simple suggestion on how to deal with testing the same language against multiple program sets, possibly kompiled with different options:

Step 1) If a language definition appears twice with different kompile options but without different -d options, then issue an error: "Definition X tested twice, with different kompile options but with the same target directory. To avoid race conditions on generated files, use a different kompilation folder (with the -d option both in kompile and in krun) for each test of the same definition which has different kompile options."

Step 2) Then collect a SET, and not a list, of kompile commands.

**Comment by andreiarusoaie** [comment]
I think it is a good idea for Daejun to work on it since I'll be busy the next period and I cannot work on it. Moreover I do not plan to work on it in the future because, at some point, I'll have to start working for my thesis.

@daejunpark : We can have some meetings if you want and discuss the implementation of ktest and what needs to be improved. Please feel free to ask me anything you want about ktest.

**Comment by daejunpark** [comment]
@grosu Ok, I'll look at it. But, please allow me have a sufficient time to be familiar with the ktest, which is helpful not only this problem but also other issues. Also, I want to design a nice structure for dealing with all of the issues smoothly.

@andreiarusoaie Thanks in advance for your help. First I'm going to look at it by myself, and then I'll ask you something that I cannot understand it.

**Comment by daejunpark** [comment]
Now it was shaped as @grosu said.
- Duplicated K definitions, if they have same kompile option, are dealt with only once by both kompile and pdf.
- If multiple K definitions have different kompile option, then error is occurred.
- With different "directory" attributes, we can avoid the above error.
- All paths are considered in their canonical form. For example, '/path/to/a' is equal to '/path/to/b/../a'.
- Although '--skip' is provided, kompile is executed when the corresponding *-kompiled does not exist. Now you can always use '--skip kompile' option without any concern.

One thing that was not attended is to respect 80 byte width for log messages. It will be fixed soon.
