### ISSUE TITLE
Parsing error when I define a constructor as Value(K)

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#925]
If I have the following definition:

```
module LLVM-SYNTAX

    syntax LLVM ::= Value(K)
endmodule
```

When I try to compile the definition, I got the error as:

```
[Error] Critical: Parse error: Syntax error near unexpected character ':'
    Source: File: /home/qangel/project/k-unified/include/modules/substitution.k
    Location: (35,41,35,41)

```

The error only happens in Maude backend When I use the java backend to compile the definition, it is fine.

**Comment by radumereuta** [comment]
This is a known modularity issue (or better yet, lack of modularity).
The problem is that you are defining the terminal "Value" which can be also parsed as a meta-variable. To tell K that I want that to be part of the production, I say "Value" -> VARID {reject}. Since we don't have modules (we use the same parser everywhere) the main file gets to break the /include files.

As a simple workaround, try to rename your production to use lowercase letters.
This issue will only be fixed once we have the new module system.
