### ISSUE TITLE
The operator _in_ from set.k not parsed as expected

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#935]
The syntax definition of the operator _in_ in set.k is 

```
 syntax Bool ::= K "in" Set  
```

In my opinion, an expression like "SetItem(1) in SetItem(1)" is ill-formed and it shouldn't be parsed.
The following definition 

```
module TEST
  rule 1 => 2
  requires SetItem(1) in SetItem(1)

  configuration
    <k> 1 </k>
endmodule
```

compiles fine, but, obviously, the behaviour is not that expected:

```
$ kompile test.k 
$ krun
<k>
    1
</k>
```

**Comment by radumereuta** [comment]
Well... everything is a K, so from a type checking perspective I don't have reasons to reject it.
@grosu opinions?

**Comment by dlucanu** [comment]
This answer is not consistent with that for #930, there both terms are K, too. Moreover, if we accept this being correct, then I think that implementation of the operator `_in_` should be changed in order to get a correct behaviour. In this form is very confusing.

**Comment by dwightguth** [comment]
Sadly, this is correct behavior. It leads to bugs if you misuse it, but
that's unavoidable. Without parametric sorts, there is no way to make this
not type which does not also prevent a set from containing sets.

**Comment by traiansf** [comment]
Well, if we would change the operator to be Bool ::= SetItem "in" Set
(and the membership rule accordingly), then we would have both no danger of confusion and no parsing problems.  But I bet @grosu will oppose this change :-)

**Comment by grosu** [comment]
I actually don't.  However, for uniformity, should's we call it "inSet"?  We should have a similar one, but with a different name, for set inclusion.

Grigore

**Comment by traiansf** [comment]
For set inclusion we have something like <=Set, I believe.

The trouble with the first argument of _in_ changing from K to SetItem is that all definitions using it would have to be updated, e.g.

.... requires not(X in keys(Store))
would become
.... requires not(SetItem(X) in keys(Store))

Now that I think better, this does look strange, because SetItem is the injection of K into Set, so we kind of say here that a singleton set is in a set which should better be stated as an inclusion.

So I guess the answer to @dlucanu's question would be that inclusion would better stay as it is, but people should use <=Set if they want to use SetItem in the left-hand-side SetItem(1) <=Set SetItem(1)

**Comment by grosu** [comment]
Either is fine with me, but I still believe that we should call it inSet, or at least have its KLabel to be inSet.  I think we should avoid stealing from our users keywords that could be desirable in their languages.

Grigore
